/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 직업 정보 중 담당 역할
 */
export type AccountResultV2PositionClassification =
  (typeof AccountResultV2PositionClassification)[keyof typeof AccountResultV2PositionClassification];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountResultV2PositionClassification = {
  TEACHER: 'TEACHER',
  MANAGER: 'MANAGER',
  PRINCIPAL: 'PRINCIPAL',
  STAFF: 'STAFF',
  ETC: 'ETC',
} as const;
