/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 계정 상태
 */
export type AccountResultV2State = (typeof AccountResultV2State)[keyof typeof AccountResultV2State];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountResultV2State = {
  NORMAL: 'NORMAL',
  PAUSE: 'PAUSE',
  WITHDRAWN: 'WITHDRAWN',
} as const;
