/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { AccountV2ForUpdateOrganizationAndPositionClassification } from './accountV2ForUpdateOrganizationAndPositionClassification';

/**
 * 수정할 계정 정보
 * @nullable
 */
export type AccountV2ForUpdate = {
  /**
   * 이메일
   * @minLength 0
   * @maxLength 255
   * @nullable
   */
  email?: string | null;
  /**
   * 휴대전화 번호
   * @minLength 0
   * @maxLength 11
   * @nullable
   */
  cellPhoneNumber?: string | null;
  /**
   * 이름
   * @minLength 2
   * @maxLength 40
   * @nullable
   */
  name?: string | null;
  /**
   * 직업 정보
   * @nullable
   */
  organizationAndPositionClassification?: AccountV2ForUpdateOrganizationAndPositionClassification;
  /**
   * 근무지 이름
   * @maxLength 90
   * @nullable
   */
  workplaceName?: string | null;
  /**
   * 소속 이름
   * @maxLength 50
   * @nullable
   */
  organizationName?: string | null;
} | null;
