/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { AccountV2Join } from './accountV2Join';
import type { ProfileV2Join } from './profileV2Join';

export interface AccountJoinWithPhoneRequest {
  /**
   * 초대 코드가 있다면 초대코드 입력
   * @minLength 8
   * @maxLength 8
   */
  invitationCode?: string;
  /** (현재 기획 없음)초대한 사용자 정보가 있다면 해당 사용자의 프로필 id나 code 입력 */
  inviterProfileIdOrCode?: string;
  account: AccountV2Join;
  profile: ProfileV2Join;
}
