/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface AccountWithdrawRequest {
  /**
   * 사유를 작성한다면 사유. 없다면 null
   * @nullable
   */
  reason?: string | null;
  /**
   * 요청자 ip
   * @nullable
   */
  ip?: string | null;
}
