/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { AccountV2JoinOrganizationAndPositionClassification } from './accountV2JoinOrganizationAndPositionClassification';

/**
 * 가입할 계정 정보
 */
export interface AccountV2Join {
  /**
   * 휴대전화 번호
   * @minLength 0
   * @maxLength 11
   */
  cellPhoneNumber: string;
  /**
   * 이름
   * @minLength 2
   * @maxLength 40
   */
  name?: string;
  /**
   * 비밀번호
   * @minLength 10
   * @maxLength 2147483647
   */
  password: string;
  /**
   * 가입요청한 ip 정보
   * @minLength 0
   * @maxLength 40
   */
  joinIp: string;
  /** 직업 정보 */
  organizationAndPositionClassification: AccountV2JoinOrganizationAndPositionClassification;
  /**
   * 근무지 이름
   * @maxLength 90
   */
  workplaceName?: string;
  /**
   * 소속 이름
   * @maxLength 50
   */
  organizationName?: string;
}
