/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 직업 정보
 */
export type AccountV2JoinOrganizationAndPositionClassification =
  (typeof AccountV2JoinOrganizationAndPositionClassification)[keyof typeof AccountV2JoinOrganizationAndPositionClassification];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountV2JoinOrganizationAndPositionClassification = {
  NURSERY_TEACHER: 'NURSERY_TEACHER',
  KINDERGARTEN_TEACHER: 'KINDERGARTEN_TEACHER',
  ELEMENTRAY_SCHOOL_TEACHER: 'ELEMENTRAY_SCHOOL_TEACHER',
  MANAGER: 'MANAGER',
  CONTRIBUTOR: 'CONTRIBUTOR',
  ETC: 'ETC',
} as const;
