/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 직업 정보 중 기관 구분
 */
export type AccountResultV2OrganiztionClassification =
  (typeof AccountResultV2OrganiztionClassification)[keyof typeof AccountResultV2OrganiztionClassification];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountResultV2OrganiztionClassification = {
  NURSERY: 'NURSERY',
  KINDERGARTEN: 'KINDERGARTEN',
  ELEMENTRAY_SCHOOL: 'ELEMENTRAY_SCHOOL',
  ISCREAM_OUTSOURCING: 'ISCREAM_OUTSOURCING',
  ISCREAM_INHOUSE: 'ISCREAM_INHOUSE',
  ETC: 'ETC',
} as const;
