/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { AccountResultV2State } from './accountResultV2State';
import type { AccountResultV2OrganizationAndPositionClassification } from './accountResultV2OrganizationAndPositionClassification';
import type { AccountResultV2OrganiztionClassification } from './accountResultV2OrganiztionClassification';
import type { AccountResultV2PositionClassification } from './accountResultV2PositionClassification';
import type { ProfileResult } from './profileResult';

export interface AccountResultV2 {
  id: number;
  /** 계정 상태 */
  state: AccountResultV2State;
  /** 이메일 */
  email?: string;
  /** 이름 */
  name: string;
  /** 휴대전화 번호 */
  cellPhoneNumber: string;
  /** 수정일 */
  modifiedAt: string;
  /** 가입일 */
  joinedAt: string;
  /** 가입 당시 ip */
  joinedIp: string;
  /** 탈퇴일 */
  withdrawnAt?: string;
  /** 탈퇴 신청시 ip */
  withdrawnIp?: string;
  /** 태그비서 여부 */
  secretarial: boolean;
  /** 직업 정보 */
  organizationAndPositionClassification: AccountResultV2OrganizationAndPositionClassification;
  /** 직업 정보 중 기관 구분 */
  organiztionClassification: AccountResultV2OrganiztionClassification;
  /** 직업 정보 중 담당 역할 */
  positionClassification: AccountResultV2PositionClassification;
  /** 근무지 이름 */
  workplaceName?: string;
  /** 소속 이름 */
  organizationName?: string;
  /** 연결된 프로필 정보 */
  profiles?: ProfileResult[];
}
