/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface AccountPasswordChangeRequest {
  /**
   * 변경할 비밀번호.
   * @minLength 10
   * @maxLength 2147483647
   */
  newPassword: string;
  /**
   * 요청하는 장비의 ip.
   * @minLength 0
   * @maxLength 40
   */
  ip: string;
}
