/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { StudentResult } from './studentResult';

export interface ApiResponseListStudentResult {
  status: number;
  result?: StudentResult[];
  timestamp?: string;
  error?: string;
  debug?: string;
}
