/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { InvitationV2Result } from './invitationV2Result';

export interface ApiResponseInvitationV2Result {
  status: number;
  result?: InvitationV2Result;
  timestamp?: string;
  error?: string;
  debug?: string;
}
