/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { FollowResult } from './followResult';

export interface ApiResponseListFollowResult {
  status: number;
  result?: FollowResult[];
  timestamp?: string;
  error?: string;
  debug?: string;
}
