/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface AuthSessionResult {
  id: number;
  token: string;
  accountId: number;
  profileId: number;
  secretarial: boolean;
  deviceModelName: string;
  refreshInterval: number;
  createdAt: string;
  createdIp: string;
  expiredAt: string;
  refreshedAt: string;
  refreshedIp: string;
}
