/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type BadgeResultState = (typeof BadgeResultState)[keyof typeof BadgeResultState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BadgeResultState = {
  NORMAL: 'NORMAL',
  STOPPED: 'STOPPED',
} as const;
