/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { BadgeResultState } from './badgeResultState';

/**
 * 프로필 뱃지 정보.(드라이브용)
 */
export interface BadgeResult {
  id: number;
  state: BadgeResultState;
  name: string;
  imageUrl: string;
  issueCount: number;
  createdAt: string;
}
