/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetByPhoneNumber1Params = {
  /**
   * 포함해서 받을 정보. profiles : 프로필 정보까지 포함
   */
  includes?: string | null;
};
