/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetEducationalClassByIdParams = {
  /**
   * 조회에 포함할 정보. students:포함된 학생 리스트 같이 조회
   */
  includes?: string;
};
