/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetStudentFaceVectorListParams = {
  /**
   * 아이 분류 요청시 전달받은 profileCode
   */
  profileCode?: string;
};
