/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface InvitationResult {
  id: number;
  code: string;
  guestName: string;
  guestCellPhoneNumber: string;
  accountId: number;
  usedAt?: string;
  usedIp?: string;
  creatorId: number;
  createdAt: string;
}
