/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface InvitationV2Result {
  /** 초대장 id */
  id: number;
  /** 초대장 code */
  code: string;
  /** 초대받은 사용자의 이름. */
  guestName: string;
  /** 초대받은 사용자의 휴대전화 번호 */
  guestCellPhoneNumber: string;
  /** 초대한 사용자의 프로필 code */
  invitationCreatorProfileCode: string;
  /** 초대한 사용자의 프로필명(닉네임) */
  invitationCreatorProfileName: string;
  /** 초대 코드가 사용된 일시 */
  usedAt?: string;
  /** 초대 코드로 가입 가능 여부 */
  isValid: boolean;
  /** 초대 코드로 가입한 ip */
  usedIp?: string;
  /** 초대 코드로 생성일 */
  createdAt: string;
  valid?: boolean;
}
