/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 사진 fileObjectId와 url 리스트. (얼굴 정면, 옆면, 윗면 등 등록용. 프로필용으로 올리면 fileObject.host/fileObject.bucket/fileObject.key가 url)
 */
export interface PhotoFileIdAndUrl {
  /** 사진 fileObject.id */
  photoFileObjectId: number;
  /** 사진 url 프로필용으로 올리면 fileObject.host/fileObject.bucket/fileObject.key가 url) */
  imageUrl: string;
}
