/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface ProfilesByCodesRequest {
  /**
   * @minItems 1
   * @maxItems 50
   */
  codes: string[];
}
