/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 가입할 프로필 정보
 */
export interface ProfileV2Join {
  /**
   * 닉네임
   * @minLength 2
   * @maxLength 40
   */
  name: string;
}
