/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { ProfileResultState } from './profileResultState';
import type { BadgeResult } from './badgeResult';

/**
 * 연결된 프로필 정보
 */
export interface ProfileResult {
  /** 프로필 id */
  id: number;
  /** 프로필 code */
  code: string;
  /** 프로필이 속한 계정 id */
  accountId: number;
  /** 상태 (1 : 정상, 100 : 일시중지, 255 : 탈퇴) */
  state: ProfileResultState;
  /** 프로필명(닉네임) */
  name: string;
  /** 프로필 소개글 */
  bio?: string;
  /** 프로필 사진의 file object id */
  photoObjectId: number;
  /** 프로필 사진의 url */
  photoUrl?: string;
  /** 프로필 수정일시 */
  modifiedAt: string;
  /** 프로필 생성일시 */
  createdAt: string;
  /** 프로필 뱃지 정보.(드라이브용) */
  badges?: BadgeResult[];
  /** 기본반의 id. (educationalClass.id) */
  basicClassId?: number;
  /** 팔로잉 수 */
  followingCount: number;
  /** 팔로워 수 */
  followerCount: number;
  /**
   * 마이보드의 배경 url. 정한게 없다면 디폴트로 무언가를 보여주기
   * @nullable
   */
  myBoardBannerUrl?: string | null;
  /**
   * 다른 사람의 프로필을 조회 했을때 조회 한 사람이 팔로잉을 하고 있는지 여부
   * @nullable
   */
  followdingState?: boolean | null;
}
