/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 수정할 프로필 정보
 * @nullable
 */
export type ProfileV2ForUpdate = {
  /**
   * 프로필 아이디. 1차는 프로필과 계정이 1:1이니까 일단 옵셔널
   * @nullable
   */
  profileId?: number | null;
  /**
   * 닉네임
   * @minLength 2
   * @maxLength 40
   * @nullable
   */
  name?: string | null;
  /**
   * 프로필 소개글
   * @minLength 1
   * @maxLength 200
   * @nullable
   */
  bio?: string | null;
} | null;
