/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface RefreshAuthSessionRequest {
  /**
   * @minLength 0
   * @maxLength 40
   */
  ip: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  deviceModelName: string;
}
