/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface SignInRequest {
  /**
   * @minLength 6
   * @maxLength 255
   * @pattern ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$
   */
  email: string;
  /**
   * @minLength 10
   * @maxLength 2147483647
   */
  password: string;
  /**
   * @minLength 0
   * @maxLength 40
   */
  ip: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  deviceModelName: string;
}
