/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface SignInWithPhoneRequest {
  /**
   * 핸드폰 번호 (샘플은 개발서버용 계정 정보)
   * @minLength 0
   * @maxLength 11
   */
  phoneNumber: string;
  /**
   * 비밀번호
   * @minLength 10
   * @maxLength 2147483647
   */
  password: string;
  /**
   * 접속 시도하는 ip
   * @minLength 0
   * @maxLength 40
   */
  ip: string;
  /**
   * 접속 시도하는 디바이스의 정보(user agent)
   * @minLength 0
   * @maxLength 500
   */
  deviceModelName: string;
}
