/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface StudentMoveRequest {
  /** 요청한 사용자의 프로필 아이디 */
  requestedProfileId: number;
  /** 현재 포함된 반 아이디 */
  from: number;
  /** 이동시킬 반 아이디 */
  to: number;
}
