/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 학생에 등록 상태. NORMAL : 정상, GRADUATE:졸업, LEAVED:퇴소
 */
export type StudentAddRequestState = (typeof StudentAddRequestState)[keyof typeof StudentAddRequestState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudentAddRequestState = {
  NORMAL: 'NORMAL',
  GRADUATE: 'GRADUATE',
  LEAVED: 'LEAVED',
} as const;
