/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 변경할 상태. NORMAL : 정상, GRADUATE:졸업, LEAVED:퇴소
 */
export type StudentUpdateRequestState = (typeof StudentUpdateRequestState)[keyof typeof StudentUpdateRequestState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudentUpdateRequestState = {
  NORMAL: 'NORMAL',
  GRADUATE: 'GRADUATE',
  LEAVED: 'LEAVED',
} as const;
