/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface StudentFaceVectorResult {
  /** 스누아이용 학생 id */
  id: number;
  /**
   * 학생의 이름, 킨더보드용 있는데 일단 어떻게 쓰실지 몰라서 별도로 설정
   * @maxLength 40
   * @nullable
   */
  name: string | null;
  /** 벡터 */
  featureVector: number[];
  /** 벡터 버전. 어떻게 쓰실지 몰라서 일단 문자열로 */
  vectorVersion: string;
  /**
   * 이미지 경로
   * @nullable
   */
  imagePath: string | null;
  /** 킨더보드의 학생 id */
  studentId: number;
}
