/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface StudentVectorDeleteRequest {
  /** 스누아이용 학생 id */
  id: number;
  /** 킨더보드의 학생 id */
  studentId: number;
}
