/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { StudentAddRequestState } from './studentAddRequestState';
import type { StudentAddRequestGender } from './studentAddRequestGender';
import type { PhotoFileIdAndUrl } from './photoFileIdAndUrl';

export interface StudentAddRequest {
  /**
   * 학생의 이름
   * @maxLength 40
   */
  name: string;
  /**
   * 학생의 생년월일
   * @maxLength 10
   */
  birthday?: string;
  /** 학생에 등록 상태. NORMAL : 정상, GRADUATE:졸업, LEAVED:퇴소 */
  state: StudentAddRequestState;
  /**
   * 학생의 사진 썸네일의 url
   * @maxLength 255
   */
  thumbUrl?: string;
  /** 성별 정보. 0,1,2나 UNKNOWN,MALE,FEMALE로 입력 */
  gender: StudentAddRequestGender;
  /** 사진 fileObjectId와 url 리스트. (얼굴 정면, 옆면, 윗면 등 등록용. 프로필용으로 올리면 fileObject.host/fileObject.bucket/fileObject.key가 url) */
  photoFileInfos?: PhotoFileIdAndUrl[];
}
