/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Member API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface UnfollowRequest {
  /** 팔로잉 프로필 ID 또는 Code */
  followingProfileIdOrCode: string;
}
