/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Core API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { AbusingReportResultContentType } from './abusingReportResultContentType';
import type { AbusingReportResultContentApiType } from './abusingReportResultContentApiType';
import type { AbusingReportResultStatus } from './abusingReportResultStatus';
import type { AbusingReportResultHandleMethod } from './abusingReportResultHandleMethod';

export interface AbusingReportResult {
  /** 신고서 ID */
  id?: number;
  /** 신고 대상 유형 (USER: 사용자, CONTENT: 자료, REPLY: 댓글) */
  contentType: AbusingReportResultContentType;
  /** 대상 SmartFolderApiType */
  contentApiType: AbusingReportResultContentApiType;
  /** 대상 SmartFolderItem ID */
  contentId?: number;
  /** 신고내용 */
  reportContents?: string;
  /** 상태 (REPORT: 신고, PROCESS: 처리중, COMPLETE: 처리 완료, HOLDING: 보류, CANCEL: 취소) */
  status: AbusingReportResultStatus;
  /** 신고자 ID */
  reporterAccountId?: number;
  /** 처리자 ID */
  adminAccountId?: number;
  /** 처리 일시 */
  handledAt?: string;
  /** 처리 방법 유형 (NO_ISSUE: 이상 없음, HOLDING: 보류, WARNING: 경고, DELETE: 삭제) */
  handleMethod?: AbusingReportResultHandleMethod;
  /** 처리 내용 메모 */
  adminNote?: string;
  /** 수정일 */
  modifiedAt?: string;
  /** 신고일 */
  createdAt?: string;
}
