/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Core API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 처리 방법 유형 (NO_ISSUE: 이상 없음, HOLDING: 보류, WARNING: 경고, DELETE: 삭제)
 */
export type AbusingReportResultHandleMethod =
  (typeof AbusingReportResultHandleMethod)[keyof typeof AbusingReportResultHandleMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AbusingReportResultHandleMethod = {
  NO_ISSUE: 'NO_ISSUE',
  HOLDING: 'HOLDING',
  WARNING: 'WARNING',
  DELETE: 'DELETE',
} as const;
