/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Core API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 상태 (REPORT: 신고, PROCESS: 처리중, COMPLETE: 처리 완료, HOLDING: 보류, CANCEL: 취소)
 */
export type AbusingReportResultStatus = (typeof AbusingReportResultStatus)[keyof typeof AbusingReportResultStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AbusingReportResultStatus = {
  REPORT: 'REPORT',
  PROCESS: 'PROCESS',
  COMPLETE: 'COMPLETE',
  HOLDING: 'HOLDING',
  CANCEL: 'CANCEL',
} as const;
