/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Core API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { AbusingReportOptionResult } from './abusingReportOptionResult';

export interface ApiResponseListAbusingReportOptionResult {
  status: number;
  result?: AbusingReportOptionResult[];
  timestamp?: string;
  error?: string;
  debug?: string;
}
