/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Core API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { TaskExampleResult } from './taskExampleResult';

export interface ApiResponseListTaskExampleResult {
  status: number;
  result?: TaskExampleResult[];
  timestamp?: string;
  error?: string;
  debug?: string;
}
