/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Core API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { MyBannerResult } from './myBannerResult';

export interface ApiResponseListMyBannerResult {
  status: number;
  result?: MyBannerResult[];
  timestamp?: string;
  error?: string;
  debug?: string;
}
