/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Core API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { CreateAbusingReportRequestContentType } from './createAbusingReportRequestContentType';
import type { CreateAbusingReportRequestContentSmartFolderApiType } from './createAbusingReportRequestContentSmartFolderApiType';

export interface CreateAbusingReportRequest {
  /** 신고 대상 유형 (USER: 사용자, CONTENT: 자료, REPLY: 댓글) */
  contentType: CreateAbusingReportRequestContentType;
  /**
   * 신고 대상 SmartFolderApiType
   * @nullable
   */
  contentSmartFolderApiType?: CreateAbusingReportRequestContentSmartFolderApiType;
  /** 신고 대상 smartFolderItem.id */
  contentId: number;
  /**
   * 신고 내용
   * @minLength 2
   * @maxLength 500
   */
  reportContents: string;
  /** 신고자 ID */
  reporterAccountId: number;
  /**
   * 신고자 IP주소
   * @minLength 0
   * @maxLength 40
   */
  createdIp: string;
}
