/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Core API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 신고 대상 SmartFolderApiType
 * @nullable
 */
export type CreateAbusingReportRequestContentSmartFolderApiType =
  | (typeof CreateAbusingReportRequestContentSmartFolderApiType)[keyof typeof CreateAbusingReportRequestContentSmartFolderApiType]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateAbusingReportRequestContentSmartFolderApiType = {
  None: 'None',
  Photo: 'Photo',
  EducationalData: 'EducationalData',
  UserFolder: 'UserFolder',
  MyBoard: 'MyBoard',
  PublicItem: 'PublicItem',
  Reply: 'Reply',
  Trashcan: 'Trashcan',
  Drive: 'Drive',
} as const;
