/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Core API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { MyBannerResultBannerType } from './myBannerResultBannerType';

export interface MyBannerResult {
  /** 베너의 id */
  id: number;
  /** 베너의 종류 */
  bannerType: MyBannerResultBannerType;
  /** 베너의 url, 보통 이미지로 예상 */
  bannerUrl: string;
  /** 기본 이미지 여부 */
  isDefuault: boolean;
  defuault?: boolean;
}
