/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Core API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 베너의 종류
 */
export type MyBannerResultBannerType = (typeof MyBannerResultBannerType)[keyof typeof MyBannerResultBannerType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MyBannerResultBannerType = {
  MAIN: 'MAIN',
  TASK: 'TASK',
  EDUCATIONAL_DATA: 'EDUCATIONAL_DATA',
  MY_BOARD: 'MY_BOARD',
} as const;
