/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Core API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { ServiceBannerResultBannerType } from './serviceBannerResultBannerType';

export interface ServiceBannerResult {
  /** 베너의 종류 */
  bannerType: ServiceBannerResultBannerType;
  /** 베너의 url, 보통 이미지로 예상 */
  bannerUrl: string;
}
