/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Message API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { NotificationPageListableResult } from './notificationPageListableResult';

export interface ApiResponseNotificationPageListableResult {
  status: number;
  result?: NotificationPageListableResult;
  timestamp?: string;
  error?: string;
  debug?: string;
}
