/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Message API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export * from './apiResponseInteger';
export * from './apiResponseLong';
export * from './apiResponseNotificationPageListableResult';
export * from './apiResponseSmsUserValidateSendResponse';
export * from './apiResponseString';
export * from './apiResponseUserValidationCodeState';
export * from './apiResponseUserValidationCodeStateResult';
export * from './notReadsParams';
export * from './notificationPageListableResult';
export * from './notificationRequest';
export * from './notificationResult';
export * from './readsParams';
export * from './smsUserValidateRequest';
export * from './smsUserValidateSendRequest';
export * from './smsUserValidateSendResponse';
