/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Message API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface NotificationResult {
  id: number;
  receiverProfileId: number;
  displayProfileId: number;
  displayProfileName?: string;
  displayProfilePhotoUrl?: string;
  body: string;
  sentAt: string;
  readAt?: string;
}
