/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Message API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { NotificationResult } from './notificationResult';

export interface NotificationPageListableResult {
  items: NotificationResult[];
  size: number;
  nextOffset: number;
}
