/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Message API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface SmsUserValidateSendRequest {
  /** 국가코드를 포함한 사용자 핸드폰 번호(010으로 보내도 되도록 수정) */
  phoneNumber: string;
  /** 발송요청한 클라이언트 ip */
  ip: string;
  /**
   * 제한 시간 분수, 기본 3분
   * @minimum 1
   * @maximum 10
   */
  expiredIn: number;
}
