/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Message API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface SmsUserValidateRequest {
  /** 발송 요청했던 국가코드를 포함한 사용자 핸드폰 번호 */
  phoneNumber: string;
  /** 요청했던 번호로 전송된 인증 코드 */
  validateCode: string;
}
