/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 신고 대상 유형 (USER: 사용자, CONTENT: 자료, REPLY: 댓글)
 */
export type AbusingReportOptionResultContentType =
  (typeof AbusingReportOptionResultContentType)[keyof typeof AbusingReportOptionResultContentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AbusingReportOptionResultContentType = {
  USER: 'USER',
  CONTENT: 'CONTENT',
  REPLY: 'REPLY',
} as const;
