/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { AbusingReportOptionResultContentType } from './abusingReportOptionResultContentType';

export interface AbusingReportOptionResult {
  /** 신고 선택지 ID */
  id?: number;
  /** 신고 대상 유형 (USER: 사용자, CONTENT: 자료, REPLY: 댓글) */
  contentType: AbusingReportOptionResultContentType;
  /** 순서 */
  sort: number;
  /** 선택지 내용 */
  contents: string;
  /** 수정일 */
  modifiedAt?: string;
  /** 생성일 */
  createdAt: string;
}
