/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface AiBlurReqeust {
  /** 사용자의 프로필 id */
  profileId: number;
  /** 자료의 키 리스트 */
  driveItemKeys: string[];
  /**
   * ai 동작시 성공 기준으로 판단할 값. 0.00 ~ 1.00 사이
   * @nullable
   */
  threshold?: number | null;
  /**
   * 응답을 폴더로 받을지? true라면 자료를 저장하고 저장된 폴더를 응답하고 따로 요청없으면 폴더 말고 자료 자체로 응답
   * @nullable
   */
  responseWithFolder?: boolean | null;
}
