/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface AiEvaluationContent {
  /** 발달영역 문자열 */
  evaluationDomainStr: string;
  /**
   * 발달영역 코드
   * @maxLength 3
   */
  evaluationDomainCode: string;
  /** 평가지표 내용 */
  contents: string;
}
