/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { SimilarityResult } from './similarityResult';

export interface ApiResponseSimilarityResult {
  status: number;
  result?: SimilarityResult;
  timestamp?: string;
  error?: string;
  debug?: string;
}
