/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { StudentRecordCreateAiObservationResult } from './studentRecordCreateAiObservationResult';

export interface ApiResponseStudentRecordCreateAiObservationResult {
  status: number;
  result?: StudentRecordCreateAiObservationResult;
  timestamp?: string;
  error?: string;
  debug?: string;
}
