/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface ApiResponseBoolean {
  status: number;
  result?: boolean;
  timestamp?: string;
  error?: string;
  debug?: string;
}
