/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type ApiResponseUserValidationCodeStateResult =
  (typeof ApiResponseUserValidationCodeStateResult)[keyof typeof ApiResponseUserValidationCodeStateResult];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiResponseUserValidationCodeStateResult = {
  REQUESTED: 'REQUESTED',
  VALIDATED: 'VALIDATED',
  EXPIRED: 'EXPIRED',
  ALREADYVALIDATED: 'ALREADYVALIDATED',
  NOTMATCHED: 'NOTMATCHED',
  FAILED: 'FAILED',
} as const;
