/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { CdnFileResultType } from './cdnFileResultType';

export interface CdnFileResult {
  type: CdnFileResultType;
  driveItemKey: string;
  path: string;
  url?: string;
  mediaType?: string;
  size: number;
}
