/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { DriveItemMemoResultMemoType } from './driveItemMemoResultMemoType';

/**
 * 메모파일이면 메모 정보
 * @nullable
 */
export type DriveItemMemoResult = {
  /** 메모의 아이디 */
  id: number;
  /** 메모가 포함될 자료의 아이디 */
  driveItemId: number;
  /** 메모의 타입(파일로서의 메모와 사진에 첨부된 사진메모) */
  memoType: DriveItemMemoResultMemoType;
  /**
   * 메모의 제목
   * @maxLength 45
   * @nullable
   */
  title?: string | null;
  /**
   * 메모 내용
   * @maxLength 500
   */
  memo: string;
  /** 소유자 계정 Id */
  ownerAccountId: number;
  /** 소유자 프로필 Id */
  ownerProfileId: number;
  /** 생성일 */
  createdAt: string;
  /** 수정일 */
  modifiedAt: string;
} | null;
