/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 메모의 타입(파일로서의 메모와 사진에 첨부된 사진메모)
 */
export type DriveItemMemoResultMemoType =
  (typeof DriveItemMemoResultMemoType)[keyof typeof DriveItemMemoResultMemoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DriveItemMemoResultMemoType = {
  ATTACHED: 'ATTACHED',
  FILE: 'FILE',
} as const;
