/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type EducationalClassResultCourse =
  (typeof EducationalClassResultCourse)[keyof typeof EducationalClassResultCourse];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EducationalClassResultCourse = {
  KR_NURSERY: 'KR_NURSERY',
  KR_KINDERGARTEN: 'KR_KINDERGARTEN',
  KR_ELMEMENTARY_SCHOOL: 'KR_ELMEMENTARY_SCHOOL',
  NONE: 'NONE',
} as const;
