/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface EducationalClassUpdateRequest {
  /** 선생님의 프로필 id */
  teacherProfileId: number;
  /** 변경할 연도 */
  year?: number;
  /**
   * 변경할 반 이름
   * @maxLength 20
   */
  name?: string;
  /** 변경할 반아이들의 연령 */
  age?: number;
  /** 이 반을 기본반으로 지정할 것인지? */
  isBasicClass?: boolean;
  basicClass?: boolean;
}
