/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type FileObjectUploadRequestDtoSource =
  (typeof FileObjectUploadRequestDtoSource)[keyof typeof FileObjectUploadRequestDtoSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileObjectUploadRequestDtoSource = {
  FILE: 'FILE',
  THUMBNAIL: 'THUMBNAIL',
  PROFILE: 'PROFILE',
} as const;
