/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetEducationalClassesParams = {
  /**
   * 포함할 정보. students: 반에 등록된 학생정보까지 포함
   */
  includes?: string;
};
