/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetLecturePlanParams = {
  /**
   * 조회에 포함할 정보. sections > cards > driveItems. driveItems을 요청하면 모든 상위 항목 포함.
   */
  includes?: string;
};
