/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetStudentParams = {
  /**
   * 조회에 포함할 정보. images:등록된 이미지 정보, educationalClass:포함된 반정보
   */
  includes?: string;
};
