/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetStudentsParams = {
  /**
   * 조회에 포함할 정보. 아직 정해진 내용 없음
   */
  includes?: string;
};
