/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetUploadedFilesParams = {
  /**
   * 검색할 타입이있다면 전달. (or검색)
   */
  fileTypes?: string | null;
  /**
   * 검색할 날짜가 있다면 시작일
   */
  startsAt?: string | null;
  /**
   * 검색할 날짜가 있다면 종료일
   */
  endsAt?: string | null;
  /**
   * 페이징 설정 페이지(0부터),한 페이지에 나올 수.
   */
  offsetWithLimit?: string;
  /**
   * 정렬 설정. 필드.정렬방법으로 요청
   */
  sorts?: string;
};
