/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface LecturePlanReportCreateSubjectAndEtcWithAiResponse {
  /**
   * ai 가 생성한 주제
   * @maxLength 20
   */
  subject: string;
  /** ai 가 생성한 목표(놀이 속 배움) */
  objective: string;
  /** 교사 지원 내용 */
  support: string;
  /**
   * 놀이계획 시작일(yyyy-MM-dd)
   * @maxLength 10
   */
  startsAt: string;
  /**
   * 놀이계획 종료일(yyyy-MM-dd)
   * @maxLength 10
   */
  endsAt: string;
}
