/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 활동시간 타입
 */
export type LecturePlanResultActivityTime =
  (typeof LecturePlanResultActivityTime)[keyof typeof LecturePlanResultActivityTime];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LecturePlanResultActivityTime = {
  MINUTES_20: 'MINUTES_20',
  MINUTES_40: 'MINUTES_40',
  MINUTES_60: 'MINUTES_60',
  DAYS_1: 'DAYS_1',
  DAYS_3: 'DAYS_3',
  DAYS_5: 'DAYS_5',
  WEEKS_2: 'WEEKS_2',
  WEEKS_3: 'WEEKS_3',
  WEEKS_4: 'WEEKS_4',
  MINUTES_30: 'MINUTES_30',
} as const;
