/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 놀이계획을 어떤 테마로 만들지. TYPE_A or TYPE_B or TYPE_C
 * @nullable
 */
export type LecturePlanCreateWithAiRequestRequestCreationType =
  | (typeof LecturePlanCreateWithAiRequestRequestCreationType)[keyof typeof LecturePlanCreateWithAiRequestRequestCreationType]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LecturePlanCreateWithAiRequestRequestCreationType = {
  TYPE_A: 'TYPE_A',
  TYPE_B: 'TYPE_B',
  TYPE_C: 'TYPE_C',
} as const;
