/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface LecturePlanReportCreatePhotoCaptionWithAiRequest {
  /**
   * 테스트용으로 호출하는지 확인합니다. false일경우 실제 ai로 데이터를 생성합니다. 필드아예 전달하지 않으시면 추후 서버 배포하면서 기본값 바꾸거나 필드를 삭제할 예정입니다.
   * @nullable
   */
  testSession?: boolean | null;
  /**
   * 놀이계획의 주제 키워드
   * @maxLength 20
   */
  subject: string;
  /**
   * 놀이 계획의 대상 연령
   * @nullable
   */
  studentAge?: number | null;
  /**
   * 놀이계획 시작일(yyyy-MM-dd)
   * @maxLength 10
   * @nullable
   */
  startsAt?: string | null;
  /**
   * 놀이계획 종료일(yyyy-MM-dd)
   * @maxLength 10
   * @nullable
   */
  endsAt?: string | null;
  /**
   * 사진의 driveItemKey  (referenceDriveItemKey나 imageUrl 둘 중 하나만 입력)
   * @nullable
   */
  referenceDriveItemKey?: string | null;
  /**
   * 사진의 url  (referenceDriveItemKey나 imageUrl 둘 중 하나만 입력)
   * @nullable
   */
  imageUrl?: string | null;
  /**
   * 레퍼런스로 쓸 놀이카드의 id (lecturePlan.id).
   * @nullable
   */
  referencePlanCardId?: number | null;
  /**
   * 레퍼런스로 쓸 메모의 자료 키 (driveItemKey).
   * @nullable
   */
  referenceMemoKey?: string | null;
  /**
   * 레퍼런스로 쓸 메모의 내용. referenceMemoKey나 이거 둘 중 하나 입력하기.
   * @nullable
   */
  referenceMemoText?: string | null;
}
