/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 직업 정보 ( NURSERY_TEACHER : 어린이집 교사,KINDERGARTEN_TEACHER : 유치원 교사, MANAGER : 관리자, ETC : 기타
 */
export type MobileAccountJoinWithPhoneRequestOrganizationAndPositionClassification =
  (typeof MobileAccountJoinWithPhoneRequestOrganizationAndPositionClassification)[keyof typeof MobileAccountJoinWithPhoneRequestOrganizationAndPositionClassification];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MobileAccountJoinWithPhoneRequestOrganizationAndPositionClassification = {
  NURSERY_TEACHER: 'NURSERY_TEACHER',
  KINDERGARTEN_TEACHER: 'KINDERGARTEN_TEACHER',
  ELEMENTRAY_SCHOOL_TEACHER: 'ELEMENTRAY_SCHOOL_TEACHER',
  MANAGER: 'MANAGER',
  CONTRIBUTOR: 'CONTRIBUTOR',
  ETC: 'ETC',
} as const;
