/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { AccountV2ForUpdate } from './accountV2ForUpdate';
import type { ProfileV2ForUpdate } from './profileV2ForUpdate';

export interface MobileAccountUpdateRequestV2 {
  account?: AccountV2ForUpdate;
  profile?: ProfileV2ForUpdate;
}
