/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { MobileUploadCompleteRequestFileObjectSource } from './mobileUploadCompleteRequestFileObjectSource';

export interface MobileUploadCompleteRequest {
  /** 저장할 파일 이름 */
  name: string;
  /** 저장할 파일의 성격. (FILE : 파일, THUMBNAIL:썸네일, PROFILE : 프로필 사진 ) */
  fileObjectSource: MobileUploadCompleteRequestFileObjectSource;
  /** 저장할 파일 FileObject.Id (Presinged url 요청시 응답받는 result 하위의 id) */
  mainFileObjectId: number;
  /** 저장할 파일의 사이즈 (byte) */
  mainFileSize: number;
  /**
   * 저장할 파일의 썸네일 FileObject.Id
   * @nullable
   */
  thumbObjectId?: number | null;
  /**
   * 태깅한 아이가 있다면 그 아이의 id 리스트 null이나 빈 리스트로 오면 기존에 태깅된 내용 삭제
   * @nullable
   */
  taggedStudentIds?: (number | null)[] | null;
}
