/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface MobileCdnFileDownloadRequest {
  /** 다운로드를 하고자하는 자료들의 키 값 리스트 */
  driveItemKeys: string[];
  /** url의 유지할 분 수 */
  period: number;
}
