/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface MobileEducationalClassAddRequest {
  /** 연도 */
  year: number;
  /**
   * 반 이름
   * @maxLength 20
   */
  name: string;
  /** 반 학생들의 나이 */
  age: number;
  /**
   * 기본 반 인지여부, false로 보내도 등록된 반이 없다면 자동으로 true. true로 보냈을 때 이미 다른 반이 있다면 이 반으로 기본 반 변경.
   * @nullable
   */
  isBasicClass?: boolean | null;
  basicClass?: boolean;
}
