/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { MobileMemoFileUpdateRequestSmartFolderApiType } from './mobileMemoFileUpdateRequestSmartFolderApiType';

export interface MobileMemoFileUpdateRequest {
  /** 자료가 속한 api 종류 */
  smartFolderApiType: MobileMemoFileUpdateRequestSmartFolderApiType;
  /** 자료의 id */
  smartFolderItemId: number;
  /**
   * 메모의 제목
   * @maxLength 45
   * @nullable
   */
  title?: string | null;
  /**
   * 메모 내용
   * @maxLength 500
   */
  memo: string;
  /**
   * 태깅한 아이가 있다면 그 아이의 id
   * @nullable
   */
  taggedStudentIds?: (number | null)[] | null;
}
