/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 자료가 속한 api 종류
 */
export type MobileMemoFileUpdateRequestSmartFolderApiType =
  (typeof MobileMemoFileUpdateRequestSmartFolderApiType)[keyof typeof MobileMemoFileUpdateRequestSmartFolderApiType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MobileMemoFileUpdateRequestSmartFolderApiType = {
  Photo: 'Photo',
  EducationalData: 'EducationalData',
  UserFolder: 'UserFolder',
  MyBoard: 'MyBoard',
  PublicItem: 'PublicItem',
  Reply: 'Reply',
  Trashcan: 'Trashcan',
  Drive: 'Drive',
} as const;
