/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { MobileAccountJoinWithPhoneRequestOrganizationAndPositionClassification } from './mobileAccountJoinWithPhoneRequestOrganizationAndPositionClassification';

export interface MobileAccountJoinWithPhoneRequest {
  /**
   * 초대 코드가 있다면 초대코드 입력
   * @minLength 8
   * @maxLength 8
   */
  invitationCode?: string;
  /** (현재 기획 없음)초대한 사용자 정보가 있다면 해당 사용자의 프로필 id나 code 입력 */
  inviterProfileIdOrCode?: string;
  /** (암호화) 휴대전화 번호 */
  cell: string;
  /** (암호화) 이름 */
  name?: string;
  /**
   * (암호화) 비밀번호
   * @minLength 10
   */
  password: string;
  /**
   * 프로필 닉네임
   * @minLength 2
   * @maxLength 40
   */
  nickname: string;
  /** 직업 정보 ( NURSERY_TEACHER : 어린이집 교사,KINDERGARTEN_TEACHER : 유치원 교사, MANAGER : 관리자, ETC : 기타 */
  organizationAndPositionClassification: MobileAccountJoinWithPhoneRequestOrganizationAndPositionClassification;
  /**
   * (암호화) 근무지 이름
   * @maxLength 90
   */
  workplaceName?: string;
  /**
   * (암호화) 소속 이름
   * @maxLength 50
   */
  organizationName?: string;
}
