/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface MobileResetPasswordRequest {
  /** (암호화) 인증번호를 받았던 사용자의 전화번호 */
  phoneNumber: string;
  /** (암호화)변경할 비밀번호. */
  newPassword: string;
}
