/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface MobileChangeAccountPasswordRequest {
  /** (암호화)변경할 비밀번호. */
  newPassword: string;
}
