/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface MobileSignInWithPhoneRequest {
  /**
   * (암호화) 핸드폰 번호 (샘플은 개발서버용 계정 정보)
   * @minLength 0
   * @maxLength 11
   */
  id: string;
  /**
   * (암호화) 비밀번호
   * @minLength 10
   * @maxLength 2147483647
   */
  password: string;
}
