/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface MobileMemoFileCreateRequest {
  /**
   * 메모의 제목
   * @maxLength 45
   * @nullable
   */
  title?: string | null;
  /**
   * 메모 내용
   * @maxLength 500
   */
  memo: string;
  /**
   * 태깅한 아이가 있다면 그 아이의 id
   * @nullable
   */
  taggedStudentIds?: (number | null)[] | null;
}
