/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface ProfileForModify {
  /**
   * 업로드 완료한 fileObject의 Id
   * @nullable
   */
  photoObjectId?: number | null;
  /**
   * 업로드 완료한 fileObject의 url. 썸네일의 경우. 객체의 host/bucket/key 로 바로 사용가능
   * @minLength 0
   * @maxLength 255
   */
  photoUrl: string;
}
