/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { SmartFolderItemResult } from './smartFolderItemResult';

/**
 * 남겨진 댓글 리스트
 * @nullable
 */
export type ReplyResult = {
  /** 댓글 ID */
  id: number;
  /** 댓글이 작성된 자료의 key (driveItem.key) */
  driveItemKey: string;
  /** 부모 댓글 */
  parentReplyId?: number;
  /** 댓글 깊이 */
  depth?: number;
  /** 댓글 상태. 현재는 0이면 정상 1이면 삭제로 처리. */
  state: number;
  /** 댓글 본문 */
  contents: string;
  /** 하위 댓글 수 */
  subReplyCount?: number;
  /** 첨부된 파일 수 */
  attachedFileCount: number;
  /** 작성자 프로필 ID */
  writerProfileId: number;
  /** 작성자 프로필 닉네임 */
  writerProfileName: string;
  /** 작성자 프로필 썸네일 url */
  writerProfileThumbUrl: string;
  /** 수정일 */
  modifiedAt?: string;
  /** 등록일 */
  createdAt?: string;
  /** 댓글 등록 파일 */
  attachedFiles?: SmartFolderItemResult[];
  /** 하위 댓글들 */
  subReplies?: ReplyResult[];
} | null;
