/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { SmartFolderItemDetailedResultRootType } from './smartFolderItemDetailedResultRootType';
import type { SmartFolderItemDetailedResultFileType } from './smartFolderItemDetailedResultFileType';
import type { SmartFolderItemDetailedResultPublicState } from './smartFolderItemDetailedResultPublicState';
import type { ReplyResult } from './replyResult';
import type { SmartFolderItemResult } from './smartFolderItemResult';
import type { DriveItemMemoResult } from './driveItemMemoResult';
import type { SmartFolderTreeResult } from './smartFolderTreeResult';
import type { LecturePlanResult } from './lecturePlanResult';
import type { LectureReportResult } from './lectureReportResult';
import type { StudentRecordResult } from './studentRecordResult';
import type { StoryBoardResult } from './storyBoardResult';

export interface SmartFolderItemDetailedResult {
  /** 스마트폴더 자료의 id */
  id: number;
  /** 스마트폴더의 루트 종류(주로 작업) */
  rootType: SmartFolderItemDetailedResultRootType;
  /** 자료의 물리적 키. (DriveItem.key */
  driveItemKey: string;
  /** 자료의 종류. URL,DOCUMENT,IMAGE,VIDEO,AUDIO,ARCHIVE,LECTURE_PLAN, ... ,ETC */
  fileType: SmartFolderItemDetailedResultFileType;
  /**
   * 자료의 이름
   * @maxLength 255
   */
  name: string;
  /** 요청한 사용자가 소유한 파일인지 여부 */
  isMine: boolean;
  /** 자료의 공개 상태. */
  publicState: SmartFolderItemDetailedResultPublicState;
  /** 소유자 프로필 Id */
  ownerProfileId: number;
  /** 자료의 실제 생성/업로드 일 */
  driveItemCreatedAt: string;
  /** 사용자가 이름을 바꾸거나 변경할 수 있는지 여부. */
  userEditable: boolean;
  /** 다른 사람이 복사한 수 */
  copyCount: number;
  /** 다른 사람이 이 자료를 조회한 수 */
  viewCount: number;
  /** 좋아요 수 */
  likeCount: number;
  /** 조회를 요청한 사용자가 좋아요를 했는지 여부 */
  hasLiked: boolean;
  /** 조회를 요청한 사용자가 즐겨찾기를 했는지 여부 */
  isFavorite: boolean;
  /** 댓글 수 */
  replyCount: number;
  /**
   * 대표사진의 url (그리드 리스트용)
   * @nullable
   */
  thumbUrl?: string | null;
  /**
   * 남겨진 댓글 리스트
   * @nullable
   */
  replyList?: ReplyResult[] | null;
  /**
   * 남겨진 댓글의 첨부파일 리스트
   * @nullable
   */
  replyAttachedFileList?: SmartFolderItemResult[] | null;
  /**
   * 남겨진 메모 리스트(추후 여러개 남길 수 있게 하겠다고 합니다. 3월엔 1개씩만)
   * @nullable
   */
  memos?: DriveItemMemoResult[] | null;
  /**
   * 추천 자료 리스트
   * @nullable
   */
  recommendItemList?: SmartFolderItemResult[] | null;
  /**
   * 태그 키워드 리스트
   * @nullable
   */
  tagList?: (string | null)[] | null;
  itemPath?: SmartFolderTreeResult;
  /**
   * 사용자 프로필 조회용 코드
   * @nullable
   */
  userProfileCode?: string | null;
  /**
   * 사용자 프로필 닉네임
   * @nullable
   */
  userProfileName?: string | null;
  /**
   * 사용자 프로필 소개글
   * @nullable
   */
  userProfileBio?: string | null;
  /**
   * 사용자 프로필 썸네일 url
   * @nullable
   */
  userProfileThumbUrl?: string | null;
  /**
   * 원본 만든 사용자의 프로필 조회용 코드
   * @nullable
   */
  authorProfileCode?: string | null;
  /**
   * 원본 만든 사용자의 프로필 닉네임
   * @nullable
   */
  authorProfileName?: string | null;
  /**
   * 원본 만든 사용자의 프로필 썸네일 url
   * @nullable
   */
  authorProfileThumbUrl?: string | null;
  /** 파일 크기(바이트) */
  totalSize: number;
  /**
   * 작업 파일이라면 작업 api에서 조회할때 사용하는 id
   * @nullable
   */
  taskId: number | null;
  lecturePlan?: LecturePlanResult;
  lecturePlanReport?: LectureReportResult;
  studentRecord?: StudentRecordResult;
  storyBoard?: StoryBoardResult;
  memoContents?: DriveItemMemoResult;
  favorite?: boolean;
}
