/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { StoryBoardContentResult } from './storyBoardContentResult';
import type { DriveItemResult } from './driveItemResult';
import type { SmartFolderItemResult } from './smartFolderItemResult';

/**
 * 스토리보드면 스토리보드 정보
 * @nullable
 */
export type StoryBoardResult = {
  /** 스토리보드의 아이디 */
  id: number;
  /**
   * 작성한 선생님의 계정 아이디
   * @minimum 0
   */
  creatorAccountId: number;
  /**
   * 작성한 선생님의 프로필 아이디
   * @minimum 0
   */
  creatorProfileId: number;
  /**
   * 제목
   * @maxLength 45
   */
  title?: string;
  /**
   * 부제목, 혹은 내용
   * @maxLength 1000
   */
  subTitle?: string;
  /**
   * 대표사진 url
   * @maxLength 1000
   */
  thumbUrl?: string;
  /** 생성일 */
  createdAt: string;
  /** 수정일 */
  modifiedAt: string;
  /** 스토리보드에 들어간 내용들 */
  contents?: StoryBoardContentResult[];
  driveItem?: DriveItemResult;
  smartFolderItem?: SmartFolderItemResult;
} | null;
