/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 태깅된 학생들
 * @nullable
 */
export type StudentResultForList = {
  /** 아이/학생의 ID */
  id: number;
  /** 아이/학생의 이름 */
  name: string;
  /** 아이/학생의 사진 url */
  thumbUrl: string;
} | null;
