/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { StudentUpdateRequestState } from './studentUpdateRequestState';
import type { StudentUpdateRequestGender } from './studentUpdateRequestGender';
import type { PhotoFileIdAndUrl } from './photoFileIdAndUrl';

export interface StudentUpdateRequest {
  /**
   * 변경할 이름
   * @maxLength 40
   */
  name?: string;
  /**
   * 변경할 생년월일
   * @maxLength 10
   */
  birthday?: string;
  /** 변경할 상태. NORMAL : 정상, GRADUATE:졸업, LEAVED:퇴소 */
  state?: StudentUpdateRequestState;
  /**
   * 변경할 사진 썸네일의 url
   * @maxLength 255
   */
  thumbUrl?: string;
  /** 변경할 성별. 0,1,2나 UNKNOWN,MALE,FEMALE로 입력 */
  gender?: StudentUpdateRequestGender;
  /** 사진 fileObjectId와 url 리스트. (얼굴 정면, 옆면, 윗면 등 등록용. 프로필용으로 올리면 fileObject.host/fileObject.bucket/fileObject.key가 url) */
  photoFileInfosToAdd?: PhotoFileIdAndUrl[];
  /** 제거할 사진 fileObjectId 리스트 */
  photoFileIdsToRemove?: number[];
}
