/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 변경할 성별. 0,1,2나 UNKNOWN,MALE,FEMALE로 입력
 */
export type StudentUpdateRequestGender = (typeof StudentUpdateRequestGender)[keyof typeof StudentUpdateRequestGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudentUpdateRequestGender = {
  UNKNOWN: 'UNKNOWN',
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;
