/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 성별 정보. 0,1,2나 UNKNOWN,MALE,FEMALE로 입력
 */
export type StudentAddRequestGender = (typeof StudentAddRequestGender)[keyof typeof StudentAddRequestGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudentAddRequestGender = {
  UNKNOWN: 'UNKNOWN',
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;
