/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { StudentResultState } from './studentResultState';
import type { StudentResultGender } from './studentResultGender';
import type { EducationalClassResult } from './educationalClassResult';
import type { PhotoFileIdAndUrl } from './photoFileIdAndUrl';

/**
 * 이 반의 학생들 정보
 */
export interface StudentResult {
  /** 아이/학생의 ID */
  id: number;
  /** 아이/학생의 이름 */
  name: string;
  /** 아이/학생의 생년월일 */
  birthday: string;
  /** 아이/학생의 상태.  */
  state: StudentResultState;
  /** 아이/학생의 사진 url */
  thumbUrl: string;
  /** 아이/학생의 성별 */
  gender: StudentResultGender;
  /** 아이/학생의 등록일 */
  createdAt: string;
  /** 아이/학생의 정보의 마지막 수정일 */
  modifiedAt?: string;
  educationalClass?: EducationalClassResult;
  /** 사진 fileObjectId와 url 리스트. (얼굴 정면, 옆면, 윗면 등 등록용. 프로필용으로 올리면 fileObject.host/fileObject.bucket/fileObject.key가 url) */
  photoFileInfos?: PhotoFileIdAndUrl[];
}
