/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 점수 모두 보내야한다고 합니다. "indicatorCode":score
 */
export type StudentRecordCreateAiObservationRequestIndicatorScores = { [key: string]: number };
