/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Ai and Proxy API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { AiEvaluationContent } from './aiEvaluationContent';

export interface StudentRecordCreateAiObservationResult {
  evaluationContents: AiEvaluationContent[];
  /** 교사 지원 내용 */
  teacherSupport: string;
  /** 학부모 지원 내용 */
  parentSupport: string;
  /** 교사 총평 내용 */
  teacherComment: string;
  /** 관찰 요약 내용 */
  observeSummary: string;
}
