/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 추가하고자 하고자하는 마이보드 탭 종류. (PLAY_PHOTO : 놀이 사진, LECTURE_PLAN : 놀이 계획, STORY_BOARD : 스토리보드)
 */
export type AddDriveItemToMyBoardRequestMyBoardType =
  (typeof AddDriveItemToMyBoardRequestMyBoardType)[keyof typeof AddDriveItemToMyBoardRequestMyBoardType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddDriveItemToMyBoardRequestMyBoardType = {
  LECTURE_PLAN: 'LECTURE_PLAN',
  LECTURE_PLAN_REPORT: 'LECTURE_PLAN_REPORT',
  STUDENT_RECORD: 'STUDENT_RECORD',
  STORY_BOARD: 'STORY_BOARD',
  STUDENT_CLASSIFICATION: 'STUDENT_CLASSIFICATION',
  ACTIVITY_CLASSIFICATION: 'ACTIVITY_CLASSIFICATION',
  PHOTO_COMPOSITION: 'PHOTO_COMPOSITION',
  PRIVATE_DATA_ENCRYPTION: 'PRIVATE_DATA_ENCRYPTION',
  SKETCH_CREATION: 'SKETCH_CREATION',
  PHOTO_ALBUM: 'PHOTO_ALBUM',
  AI_WRITING: 'AI_WRITING',
  STUDENT_AND_ACTIVITY_CLASSIFICATION: 'STUDENT_AND_ACTIVITY_CLASSIFICATION',
  PLAY_PHOTO: 'PLAY_PHOTO',
  REPLY: 'REPLY',
  ETC: 'ETC',
} as const;
