/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { AddDriveItemToMyBoardRequestMyBoardType } from './addDriveItemToMyBoardRequestMyBoardType';

export interface AddDriveItemToMyBoardRequest {
  /**
   * 추가할 요청한 사용자의 ip (추적용)
   * @minLength 1
   * @maxLength 40
   */
  folderOwnerIp: string;
  /** 추가하고자 하고자하는 마이보드 탭 종류. (PLAY_PHOTO : 놀이 사진, LECTURE_PLAN : 놀이 계획, STORY_BOARD : 스토리보드) */
  myBoardType: AddDriveItemToMyBoardRequestMyBoardType;
  /** 공개인 상태로 마이보드에 추가할지? */
  isPublic: boolean;
  /**
   * 원본 자료의 자료 키 리스트(DriveItem.key)
   * @minLength 1
   * @minItems 1
   * @maxItems 2147483647
   */
  originalDriveItemKeys: string[];
  public?: boolean;
}
