/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface AddReplyRequest {
  /** 부모 댓글 ID */
  parentId?: number;
  /**
   * 댓글 본문
   * @minLength 0
   * @maxLength 500
   */
  contents: string;
  /** 작성자 프로필 ID */
  writerProfileId: number;
  /** 등록지 IP */
  createdIp: string;
  /** 첨부파일의 driveItem.key 리스트 */
  attachedDriveItemKeyList?: string[];
}
