/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface AddStudentPhotoRequest {
  /** 저장 요청한 사용자의 프로필 id */
  folderOwnerProfileId: number;
  /**
   * 저장할 학생의 id
   * @minimum 1
   * @maximum 40
   */
  studentId: number;
  /**
   * 저장할 자료의 키 리스트
   * @minLength 1
   * @minItems 1
   * @maxItems 2147483647
   */
  targetDriveItemKeys: string[];
}
