/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { RecommendationKeywordBundleResult } from './recommendationKeywordBundleResult';

export interface ApiResponseListRecommendationKeywordBundleResult {
  status: number;
  result?: RecommendationKeywordBundleResult[];
  timestamp?: string;
  error?: string;
  debug?: string;
}
