/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { DriveItemResult } from './driveItemResult';

export interface ApiResponseDriveItemResult {
  status: number;
  result?: DriveItemResult;
  timestamp?: string;
  error?: string;
  debug?: string;
}
