/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { PublicUrlItemDetailedResult } from './publicUrlItemDetailedResult';

export interface ApiResponsePublicUrlItemDetailedResult {
  status: number;
  result?: PublicUrlItemDetailedResult;
  timestamp?: string;
  error?: string;
  debug?: string;
}
