/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { LectureReportCardAiCreationLogResult } from './lectureReportCardAiCreationLogResult';

export interface ApiResponseLectureReportCardAiCreationLogResult {
  status: number;
  result?: LectureReportCardAiCreationLogResult;
  timestamp?: string;
  error?: string;
  debug?: string;
}
