/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { CdnFileResult } from './cdnFileResult';

export interface ApiResponseListCdnFileResult {
  status: number;
  result?: CdnFileResult[];
  timestamp?: string;
  error?: string;
  debug?: string;
}
