/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 자료의 api type(smartfolderitem.smartFolderApiType
 */
export type ApiTypeAndItemIdSmartFolderApiType =
  (typeof ApiTypeAndItemIdSmartFolderApiType)[keyof typeof ApiTypeAndItemIdSmartFolderApiType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiTypeAndItemIdSmartFolderApiType = {
  Photo: 'Photo',
  EducationalData: 'EducationalData',
  UserFolder: 'UserFolder',
  MyBoard: 'MyBoard',
  PublicItem: 'PublicItem',
  Reply: 'Reply',
  Trashcan: 'Trashcan',
  Drive: 'Drive',
} as const;
