/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { ApiTypeAndItemIdSmartFolderApiType } from './apiTypeAndItemIdSmartFolderApiType';

export interface ApiTypeAndItemId {
  /** 자료의 api type(smartfolderitem.smartFolderApiType */
  smartFolderApiType: ApiTypeAndItemIdSmartFolderApiType;
  /**
   * 자료의 id(smartfolderitem.id
   * @minimum 1
   * @maximum 40
   */
  itemId: number;
}
