/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type CdnFileResultType = (typeof CdnFileResultType)[keyof typeof CdnFileResultType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CdnFileResultType = {
  FILE: 'FILE',
  FOLDER: 'FOLDER',
  PROJECT: 'PROJECT',
  SMART_FOLDER: 'SMART_FOLDER',
  MY_FOLDER: 'MY_FOLDER',
  TEMP: 'TEMP',
  ROOT: 'ROOT',
} as const;
