/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 변경할 상태
 */
export type ChangeShareStatePublicItemRequestPublicState =
  (typeof ChangeShareStatePublicItemRequestPublicState)[keyof typeof ChangeShareStatePublicItemRequestPublicState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeShareStatePublicItemRequestPublicState = {
  PRIVATE: 'PRIVATE',
  PUBLIC: 'PUBLIC',
  PRIVATE_AND_URL_SHARE: 'PRIVATE_AND_URL_SHARE',
  PUBLIC_AND_URL_SHARE: 'PUBLIC_AND_URL_SHARE',
} as const;
