/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { ChangeShareStatePublicItemRequestPublicState } from './changeShareStatePublicItemRequestPublicState';

export interface ChangeShareStatePublicItemRequest {
  /** 변경할 자료의 아이디 값. */
  publicItemId: number;
  /** 변경할 상태 */
  publicState: ChangeShareStatePublicItemRequestPublicState;
}
