/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface ChangeLinkedStudentRequest {
  /** 요청한 사용자의 사용자의 계정 id */
  itemOwnerAccountId: number;
  /** 요청한 사용자의 프로필 id */
  itemOwnerProfileId: number;
  /** 변경할 아이의 id */
  studentId: number;
  /**
   * 변경할 자료의 id 리스트
   * @minLength 1
   * @minItems 1
   * @maxItems 2147483647
   */
  targetItemIds: number[];
}
