/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { CheckNotIndexedItems2TargetType } from './checkNotIndexedItems2TargetType';

export type CheckNotIndexedItems2Params = {
  targetType: CheckNotIndexedItems2TargetType;
};
