/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { CommonAddDriveItemToSmartFolderRequestTargetSmartFolderApiType } from './commonAddDriveItemToSmartFolderRequestTargetSmartFolderApiType';

export interface CommonAddDriveItemToSmartFolderRequest {
  /** 저장 요청한 사용자의 사용자의 계정 id */
  folderOwnerAccountId: number;
  /** 저장할 요청한 사용자의 프로필 id */
  folderOwnerProfileId: number;
  /**
   * 추가할 요청한 사용자의 ip (추적용)
   * @minLength 1
   * @maxLength 40
   */
  folderOwnerIp: string;
  /** 추가할 폴더의 api 타입(Photo:사진스마트폴더, EducationalData:자료스마트폴더, UserFolder:내폴더) */
  targetSmartFolderApiType: CommonAddDriveItemToSmartFolderRequestTargetSmartFolderApiType;
  /** 추가할 내 폴더의 id */
  targetFolderId: number;
  /**
   * 원본 자료의 자료 키 리스트
   * @minLength 1
   * @minItems 1
   * @maxItems 2147483647
   */
  originalDriveItemKeys: string[];
}
