/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { CommonHideItemRequestTargetSmartFolderApiType } from './commonHideItemRequestTargetSmartFolderApiType';

export interface CommonHideItemRequest {
  /** 요청한 사용자의 프로필 id */
  itemOwnerProfileId: number;
  /** 숨길 자료들의 스마트폴더 api 타입(Photo:사진스마트폴더, EducationalData:자료스마트폴더, UserFolder:내폴더) */
  targetSmartFolderApiType: CommonHideItemRequestTargetSmartFolderApiType;
  /**
   * 숨길 자료의 id 리스트
   * @minLength 1
   * @minItems 1
   * @maxItems 2147483647
   */
  targetItemIds: number[];
}
