/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { CommonAddDriveItemToSmartFolderWithIdRequestTargetSmartFolderApiType } from './commonAddDriveItemToSmartFolderWithIdRequestTargetSmartFolderApiType';
import type { SmartfolderApiTypeAndIdRequest } from './smartfolderApiTypeAndIdRequest';

export interface CommonAddDriveItemToSmartFolderWithIdRequest {
  /**
   * 추가할 요청한 사용자의 ip (추적용)
   * @minLength 1
   * @maxLength 40
   */
  ip: string;
  /** 추가할 폴더의 api 타입(Photo:사진스마트폴더, EducationalData:자료스마트폴더, UserFolder:내폴더) */
  targetSmartFolderApiType: CommonAddDriveItemToSmartFolderWithIdRequestTargetSmartFolderApiType;
  /** 추가할 내 폴더의 id */
  targetFolderId: number;
  /**
   * 원본 자료의 자료 api type &  id 리스트
   * @minLength 1
   * @minItems 1
   * @maxItems 2147483647
   */
  origianlItemApiTypeAndId: SmartfolderApiTypeAndIdRequest[];
}
