/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { CommonMoveItemRequestTargetSmartFolderApiType } from './commonMoveItemRequestTargetSmartFolderApiType';
import type { CommonMoveItemRequestOriginalSmartFolderApiType } from './commonMoveItemRequestOriginalSmartFolderApiType';

export interface CommonMoveItemRequest {
  /** 요청한 사용자의 사용자의 계정 id */
  itemOwnerAccountId: number;
  /** 요청한 사용자의 프로필 id */
  itemOwnerProfileId: number;
  /** 이동할(목적지) 폴더의 api 타입(Photo:사진스마트폴더, EducationalData:자료스마트폴더, UserFolder:내폴더) */
  targetSmartFolderApiType: CommonMoveItemRequestTargetSmartFolderApiType;
  /** 이동할(목적지) 폴더의 id */
  targetFolderId: number;
  /** 이동을 해야하는 폴더의 api 타입 */
  originalSmartFolderApiType: CommonMoveItemRequestOriginalSmartFolderApiType;
  /**
   * 이동을 해야하는 자료의 id 리스트
   * @minLength 1
   * @minItems 1
   * @maxItems 2147483647
   */
  originalItemIds: number[];
}
