/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { CommonChangeShareStateWithDriveItemKeyRequestPublicState } from './commonChangeShareStateWithDriveItemKeyRequestPublicState';

export interface CommonChangeShareStateWithDriveItemKeyRequest {
  /** 변경할 자료의 물리 키 값. */
  driveItemKey: string;
  /** 변경할 상태 */
  publicState: CommonChangeShareStateWithDriveItemKeyRequestPublicState;
}
