/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { CommonRenameRequestTargetSmartFolderApiType } from './commonRenameRequestTargetSmartFolderApiType';

export interface CommonRenameRequest {
  /** 요청한 사용자의 프로필 id */
  itemOwnerProfileId: number;
  /** 변경할 자료의 스마트폴더 api 타입(Photo:사진스마트폴더, EducationalData:자료스마트폴더, UserFolder:내폴더) */
  targetSmartFolderApiType: CommonRenameRequestTargetSmartFolderApiType;
  /** 자료보드 자료의 id */
  targetItemId: number;
  /**
   * 변경할 이름
   * @minLength 1
   * @maxLength 255
   */
  nameToChange: string;
}
