/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { CommonChangeShareStateWithidRequestTargetSmartFolderApiType } from './commonChangeShareStateWithidRequestTargetSmartFolderApiType';
import type { CommonChangeShareStateWithidRequestPublicState } from './commonChangeShareStateWithidRequestPublicState';

export interface CommonChangeShareStateWithidRequest {
  /** 숨길 자료들의 스마트폴더 api 타입(Photo:사진스마트폴더, EducationalData:자료스마트폴더, UserFolder:내폴더) */
  targetSmartFolderApiType: CommonChangeShareStateWithidRequestTargetSmartFolderApiType;
  /** 변경할 자료의 아이디 값. */
  targetItemId: number;
  /** 변경할 상태 */
  publicState: CommonChangeShareStateWithidRequestPublicState;
}
