/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 특별히 저장할 경로가 있다면 목적 폴더의 api 타입(Photo:사진스마트폴더, EducationalData:자료스마트폴더, UserFolder:내폴더, MyBoard:마이 보드)
 */
export type CommonUploadCompletedRequestTargetSmartFolderApiType =
  (typeof CommonUploadCompletedRequestTargetSmartFolderApiType)[keyof typeof CommonUploadCompletedRequestTargetSmartFolderApiType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommonUploadCompletedRequestTargetSmartFolderApiType = {
  Photo: 'Photo',
  EducationalData: 'EducationalData',
  UserFolder: 'UserFolder',
  MyBoard: 'MyBoard',
  PublicItem: 'PublicItem',
  Reply: 'Reply',
  Trashcan: 'Trashcan',
  Drive: 'Drive',
} as const;
