/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 어느 기능에서 업로드를 완료 했는지?
 */
export type CommonUploadCompletedRequestUploadedTaskType =
  (typeof CommonUploadCompletedRequestUploadedTaskType)[keyof typeof CommonUploadCompletedRequestUploadedTaskType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommonUploadCompletedRequestUploadedTaskType = {
  LECTURE_PLAN: 'LECTURE_PLAN',
  LECTURE_PLAN_REPORT: 'LECTURE_PLAN_REPORT',
  STUDENT_RECORD: 'STUDENT_RECORD',
  STORY_BOARD: 'STORY_BOARD',
  STUDENT_CLASSIFICATION: 'STUDENT_CLASSIFICATION',
  ACTIVITY_CLASSIFICATION: 'ACTIVITY_CLASSIFICATION',
  PHOTO_COMPOSITION: 'PHOTO_COMPOSITION',
  PRIVATE_DATA_ENCRYPTION: 'PRIVATE_DATA_ENCRYPTION',
  SKETCH_CREATION: 'SKETCH_CREATION',
  PHOTO_ALBUM: 'PHOTO_ALBUM',
  AI_WRITING: 'AI_WRITING',
  STUDENT_AND_ACTIVITY_CLASSIFICATION: 'STUDENT_AND_ACTIVITY_CLASSIFICATION',
  PLAY_PHOTO: 'PLAY_PHOTO',
  REPLY: 'REPLY',
  ETC: 'ETC',
} as const;
