/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 숨길 자료들의 스마트폴더 api 타입(Photo:사진스마트폴더, EducationalData:자료스마트폴더, UserFolder:내폴더)
 */
export type CommonChangeShareStateWithidRequestTargetSmartFolderApiType =
  (typeof CommonChangeShareStateWithidRequestTargetSmartFolderApiType)[keyof typeof CommonChangeShareStateWithidRequestTargetSmartFolderApiType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommonChangeShareStateWithidRequestTargetSmartFolderApiType = {
  Photo: 'Photo',
  EducationalData: 'EducationalData',
  UserFolder: 'UserFolder',
  MyBoard: 'MyBoard',
  PublicItem: 'PublicItem',
  Reply: 'Reply',
  Trashcan: 'Trashcan',
  Drive: 'Drive',
} as const;
