/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface CourseResult {
  /** 파라미터로 숫자로 넣을 때 값. */
  enumCode: number;
  /** 파라미터로 문자로 넣을 때 값. */
  stringCode: string;
  /** 국가 구분.(현재는 KR만) */
  nationCode: string;
  /** 과정 이름 */
  title: string;
  /** 최소 일반 나이 */
  minAge: number;
  /** 최대 일반 나이 */
  maxAge: number;
  /** 최소 만 나이 */
  minInternationalAge: number;
  /** 최대 만 나이 */
  maxInternationalAge: number;
  /** 생성일 */
  createdAt: string;
}
