/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { CreateSmartFolderRequestParentSmartFolderApiType } from './createSmartFolderRequestParentSmartFolderApiType';

export interface CreateSmartFolderRequest {
  /**
   * 폴더 이름
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** 공개 여부 */
  public: boolean;
  /** 상위 스마트폴더의 ApiType */
  parentSmartFolderApiType: CreateSmartFolderRequestParentSmartFolderApiType;
  /** 상위 스마트폴더의 id */
  parentSmartFolderId: number;
  /** 연관된 반 id */
  educationalClassId?: number;
}
