/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface CreateMyFolderRequest {
  /** 요청하는 사용자의 계정 id */
  creatorAccountId: number;
  /** 요청하는 사용자의 프로필 id */
  creatorProfileId: number;
  /**
   * 폴더 이름
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** 공개 여부 */
  public: boolean;
  /**
   * 상위 폴더가 있다면 그 스마트폴더의 id
   * @nullable
   */
  parentSmartFolderId?: number | null;
}
