/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface CreateStudentPhotoFolderRequest {
  /** 아이의 id */
  studentId: number;
  /**
   * 아이의 이름
   * @maximum 255
   */
  studentName: string;
}
