/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 상위 스마트폴더의 ApiType
 */
export type CreateSmartFolderRequestParentSmartFolderApiType =
  (typeof CreateSmartFolderRequestParentSmartFolderApiType)[keyof typeof CreateSmartFolderRequestParentSmartFolderApiType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSmartFolderRequestParentSmartFolderApiType = {
  Photo: 'Photo',
  EducationalData: 'EducationalData',
  UserFolder: 'UserFolder',
  MyBoard: 'MyBoard',
  PublicItem: 'PublicItem',
  Reply: 'Reply',
  Trashcan: 'Trashcan',
  Drive: 'Drive',
} as const;
