/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 휴지통에 들어가 있는지 여부. 0 : 정상, 1 : 휴지통, 2 : 상위항목이 휴지통에
 */
export type DriveItemResultInTrash = (typeof DriveItemResultInTrash)[keyof typeof DriveItemResultInTrash];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DriveItemResultInTrash = {
  OUT_OF_TRASH: 'OUT_OF_TRASH',
  IN_TRASH: 'IN_TRASH',
  PARENT_IN_TRASH: 'PARENT_IN_TRASH',
} as const;
