/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface DriveItemAddTagRequest {
  /** 일괄 적용할 자료의 키 값 리스트. driveItem.key */
  keys: string[];
  /** 일괄 적용할 태그 리스트 */
  tags?: string[];
}
