/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface DriveItemLikeResult {
  /** 요청한 사용자의 좋아요 상태 */
  likeState: boolean;
  /** 대상 자료의 좋아요 수 */
  likeCount: number;
}
