/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface DriveItemSttUpdateRequest {
  /**
   * 변경할 요약
   * @nullable
   */
  sttSummary?: string | null;
  /** 변경할 내용 */
  sttFullText: string;
  /** 소유자 계정 Id */
  ownerAccountId: number;
  /** 소유자 프로필 Id */
  ownerProfileId: number;
}
