/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface DriveItemMemoUpdateRequest {
  /**
   * 변경할 제목
   * @maxLength 45
   * @nullable
   */
  title?: string | null;
  /**
   * 변경할 내용
   * @maxLength 500
   */
  memo: string;
  /** 소유자 계정 Id */
  ownerAccountId: number;
  /** 소유자 프로필 Id */
  ownerProfileId: number;
}
