/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface DriveItemChangeThumbnailRequest {
  /** 소유자 계정의 Id */
  ownerId: number;
  /** 썸네일 파일 객체의 id (fileObject.id) */
  thumbObjectId: number;
  /**
   * 직접 접근 가능한 url 정보.
   * @maxLength 1000
   */
  thumbUrl?: string;
}
