/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { DriveItemResultInTrash } from './driveItemResultInTrash';
import type { DriveItemResultType } from './driveItemResultType';
import type { DriveItemResultFileType } from './driveItemResultFileType';
import type { FileObjectResult } from './fileObjectResult';
import type { DriveItemMemoResult } from './driveItemMemoResult';

/**
 * 생성된 스토리보드의 드라이브 자료 객체정보
 */
export interface DriveItemResult {
  id: number;
  /** 자료의 키 값 */
  key: string;
  /** 휴지통에 들어가 있는지 여부. 0 : 정상, 1 : 휴지통, 2 : 상위항목이 휴지통에 */
  inTrash: DriveItemResultInTrash;
  /** 공유된 자료를 복사해 온 것이라면 원본 자료의 id */
  publishedItemId: number;
  /** 상위 항목의 id */
  parentId: number;
  /** 항목의 종류. FILE, FOLDER, PROJECT,TEMP,ROOT */
  type: DriveItemResultType;
  /** 파일의 종류. URL,DOCUMENT,IMAGE,VIDEO,AUDIO,ARCHIVE,ETC */
  fileType: DriveItemResultFileType;
  /** 실제 파일의 id */
  fileObjectId: number;
  /** 파일의 종류가 url일 경우 그 url 정보 */
  url?: string;
  /** 별도의 썸네일 url이 있을 경우. */
  thumbUrl?: string;
  /** 썸네일 파일의 id. 썸네일이나 프로필의 경우 파일객체의 {host}/{bucket}/{key}로 접근가능. */
  thumbObjectId: number;
  /** 파일의 이름 */
  name: string;
  /** 프론트 표시용. 첫 태그 이름 */
  firstTagName?: string;
  /** 태그 묶음의 id */
  tagBundleId: number;
  /** 태깅된 단어 수 */
  tagCount: number;
  /** 자료 소유자 계정의 id */
  ownerAccountId: number;
  /** 자료 소유자 프로필의 id */
  ownerProfileId: number;
  /** 중요자료 표시 여부 */
  starred: boolean;
  /** 자료 배포 회수 */
  publishedCount: number;
  /** 자료 사이즈 */
  totalSize: number;
  /** 하위 폴더의 개수 */
  folderCount: number;
  /** 하위 파일의 개수 */
  fileCount: number;
  /** 태그 비서에게 할당된 작업 id */
  taskItemId: number;
  /** 할당받은 태그 비서 계정 id */
  secretaryAccountId: number;
  /** 서비스에 최초로 업로드하거나 생성한 계정의 id */
  creatorAccountId: number;
  /** 서비스에 최초로 업로드하거나 생성한 프로필의 id */
  creatorProfileId: number;
  /** 서비스에 최초로 업로드하거나 생성한 ip */
  createdIp: string;
  /** 서비스에 최초로 업로드하거나 생성한 날짜 */
  createdAt: string;
  fileObject?: FileObjectResult;
  thumbObject?: FileObjectResult;
  /** 입력된 태그 리스트 */
  tags?: string[];
  /** stt로 전체 텍스트화 한 내용 */
  sttFullString?: string;
  /** 입려된 stt 전체 내용을를 요약한 내용 */
  sttSummary?: string;
  /** 입력된 메모의 수 */
  memoCount: number;
  /** 입력된 메모 리스트 */
  memos?: DriveItemMemoResult[];
  /** 다른 사람이 복사한(내 폴더에 저장하거나 가져간) 수 */
  copyCount: number;
  modifiedAt: string;
  /** 다른 사람이 내 자료를 열람한 수 */
  viewCount: number;
  /** 좋아요 수 */
  likeCount: number;
  /** 댓글 수 */
  replyCount: number;
  /** 사용자가 이름을 바꾸거나 변경할 수 있는지 여부. */
  userEditable: boolean;
  memoContents?: DriveItemMemoResult;
  /**
   * 자료에 태깅된 학생 id
   * @nullable
   */
  taggedStudentIds?: (number | null)[] | null;
}
