/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { FileObjectUploadRequestSource } from './fileObjectUploadRequestSource';

export interface FileObjectUploadRequest {
  /** 자료의 기본 종류 구분. FILE, THUMB, PROFILE */
  source: FileObjectUploadRequestSource;
  /**
   * 업로드할 파일의 미디어 타입
   * @minLength 1
   * @maxLength 100
   */
  mediaType: string;
  /**
   * 업로드할 원본 파일의 이름
   * @minLength 1
   * @maxLength 255
   */
  originalFileName: string;
  /**
   * 업로드할 파일의 사이즈(Byte)
   * @maximum 2147483648
   */
  size: number;
  /** 업로드 할 계정의 id */
  ownerAccountId: number;
  /**
   * 업로더의 ip
   * @minLength 1
   * @maxLength 40
   */
  createdIp: string;
}
