/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { FileObjectSttTextPostResponseState } from './fileObjectSttTextPostResponseState';

export interface FileObjectSttTextPostResponse {
  id: number;
  fileObjectId: number;
  sttFullText: string;
  sttSummary?: string;
  state: FileObjectSttTextPostResponseState;
  createdAt: string;
  modifiedAt?: string;
}
