/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type FileObjectSttTextPostResponseState =
  (typeof FileObjectSttTextPostResponseState)[keyof typeof FileObjectSttTextPostResponseState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileObjectSttTextPostResponseState = {
  UPLOADED: 'UPLOADED',
  STT_REQUESTED: 'STT_REQUESTED',
  STT_COMPLETED: 'STT_COMPLETED',
  STT_SUMMARY_REQUESTED: 'STT_SUMMARY_REQUESTED',
  STT_SUMARRY_COMPLETED: 'STT_SUMARRY_COMPLETED',
  SUSPENDED: 'SUSPENDED',
} as const;
