/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 파일의 업로드 상태, 0:업로드 전, 1: 정상(업로드완료. 다운/공유가능), 2: 삭제대기
 */
export type FileObjectResultState = (typeof FileObjectResultState)[keyof typeof FileObjectResultState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileObjectResultState = {
  PREPARE: 'PREPARE',
  NORMAL: 'NORMAL',
  WAITING_FOR_REMOVE: 'WAITING_FOR_REMOVE',
} as const;
