/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetByIdOrKeyParams = {
  /**
   * 소유자의 계정 id
   */
  owner_id: string;
  /**
   * 포함시킬 하위 정보. fileObject:파일객체, thumbObject:썸네일객체,tags:태그리스트,stt:stt인식결과,memo:입력된 메모리스트
   */
  includes?: string;
};
