/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { GetDomainsCourse } from './getDomainsCourse';

export type GetDomainsParams = {
  course: GetDomainsCourse;
};
