/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetFoldersParams = {
  /**
   * 특정 폴더 하위를 조회한다면 해당 폴더의 api type(Photo:사진스마트폴더, EducationalData:자료스마트폴더, UserFolder:내폴더)
   */
  smartFolderApiType?: string | null;
  /**
   * 특정 폴더 하위를 조회한다면 해당 폴더 id. 이때는 apiType을 꼭 같이 요청하셔야합니다.
   */
  parentSmartFolderId?: string | null;
};
