/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetItemListParams = {
  /**
   * 조회할 폴더의 api type(Photo:사진스마트폴더, EducationalData:자료스마트폴더, UserFolder:내폴더)
   */
  smartFolderApiType?: string | null;
  /**
   * 조회할 폴더의 id.
   */
  parentSmartFolderId?: string | null;
  /**
   * 조회하고자하는 파일 유형이 있다면.
   */
  targetFileType?: string | null;
  /**
   * 검색 시작일
   */
  startsAt?: string | null;
  /**
   * 검색 종료일
   */
  endsAt?: string | null;
  /**
   * 조회에 포함할 정보. driveItem : 물리정보 포함
   */
  includes?: string | null;
  /**
   * 페이징 설정 페이지(0부터),한 페이지에 나올 수.
   */
  offsetWithLimit?: string;
  /**
   * 정렬 설정. 필드.정렬방법으로 요청
   */
  sorts?: string;
};
