/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetImageFlatPathParams = {
  /**
   * 작업의 종류. STUDENT_CLASSIFICATION, ACTIVITY_CLASSIFICATION
   */
  taskType?: string;
};
