/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetItemKeyListParams = {
  /**
   * 조회할 폴더의 api type(Photo:사진스마트폴더, EducationalData:자료스마트폴더, UserFolder:내폴더)
   */
  smartFolderApiType: string | null;
  /**
   * 조회할 폴더의 id.
   */
  parentSmartFolderId: string | null;
};
