/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetItemPathTreeParams = {
  /**
   * 자료의 smartFolderApiType (UserFolder, MyBoard, Photo, EducationalData, Reply, PublicItem)
   */
  smartFolderApiType: string;
  /**
   * 자료의 id(SmartFolderItem.id)
   */
  smartFolderItemId: string;
};
