/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetImageTaskParams = {
  /**
   * 조회에 추가로 요청할 정보. inputItems : 입력에 사용한 자료, outputItems : 결과로 생성된 이미지 자료, thumbnail : 자료의 썸네일
   */
  includes?: string | null;
};
