/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetIndicatorsParams = {
  /**
   * 관리 해야하는 아이/학생의 나이
   */
  age: string;
  evaluationDomainCode?: string;
};
