/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetLectureReportParams = {
  /**
   * 조회에 포함할 정보. cards > photoItems. photoItems 요청하면 모든 상위 항목 포함. smartFolderItem : 자료보드의 자료 정보 추가로 조회
   */
  includes?: string;
};
