/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetMyBoardItemsParams = {
  /**
   * 조회하고자하는 마이보드 탭 종류. (PLAY_PHOTO : 놀이 사진, LECTURE_PLAN : 놀이 계획, STORY_BOARD : 스토리보드)
   */
  myBoardType: string;
  /**
   * 조회하고자하는 파일 유형이 있다면.
   */
  targetFileType?: string | null;
  /**
   * 공개나 비공개상태인 자료들을 조회 시 전달.
   */
  isPublic?: string | null;
  /**
   * 페이징 설정 페이지(0부터),한 페이지에 나올 수.
   */
  offsetWithLimit?: string;
  /**
   * 정렬 설정. 필드.정렬방법으로 요청
   */
  sorts?: string;
};
