/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetPhotoHomeFoldersParams = {
  educationalClassId?: number;
  /**
   * 아이분류/활동분류/빠른작업사진 불러올 하위 폴더의 개수. 기획 v1.0 기준으로 8개씩 두줄로 확인
   */
  limitPerCategory?: string;
};
