/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetPublicItem1Params = {
  /**
   * 공개자료의 id(PublicBoardItem.id 혹은 공유상태변경결과의 publicUrlItemCode)
   */
  publicBoardItemIdOrCode: string;
};
