/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetRecommendPlansParams = {
  /**
   * 요청하는 최대 개수
   */
  requestSize?: string;
};
