/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetRecommendationKeywordInfoParams = {
  /**
   * 검색할날짜, 입력없다면 당일 기준
   */
  targetDate?: string | null;
  /**
   * 검색일 기준 얼마나 더 미래의 데이터를 불러볼지?
   */
  preploadDay?: string | null;
  /**
   * 조회에 포함할 정보. keywords : 하위 등록된 키워드 리스트
   */
  includes?: string;
};
