/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetRecommendationKeywordParams = {
  /**
   * 검색할날짜, 입력없다면 당일 기준
   */
  targetDate?: string | null;
  /**
   * 검색일 기준 얼마나 더 미래의 데이터를 불러볼지?
   */
  preploadDay?: string | null;
  /**
   * 요청 받고자하는 키워드 수
   */
  requestCount?: string | null;
  /**
   * 기본 키워드(weight가 0인) 키워드도 추가해서 받을 것인지?
   */
  includeBasicKeywords?: string | null;
};
