/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetRecentTasksParams = {
  /**
   * 조회할 업무의 종류. LECTURE_PLAN, LECTURE_PLAN_REPORT, STUDENT_RECORD
   */
  taskType?: string | null;
  /**
   * 조회에 포함할 정보. driveItem : 자료항목 포함
   */
  includes?: string | null;
  /**
   * 페이징 설정 페이지(0부터),한 페이지에 나올 수.
   */
  offsetWithLimit?: string | null;
  /**
   * 정렬 설정. 필드.정렬방법으로 요청
   */
  sorts?: string | null;
};
