/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetRecommendPlansFromPublicItemsParams = {
  /**
   * 놀이계획을 조회중이라면 조회중인 놀이계획 id (lecturePlan.id)
   */
  lecturePlanId?: string | null;
  /**
   * 놀이계획을 조회중이라면 조회중인 놀이계획의 주제 (lecturePlan.subject)
   */
  lecturePlanSubject?: string | null;
  /**
   * 놀이계획을 조회중이라면 조회중인 놀이계획의 주요활동명들 (lecturePlan.activityNames)
   */
  lecturePlanActivityNames?: string | null;
  /**
   * 놀이계획을 조회중이라면 조회중인 놀이계획의 대상연령 (lecturePlan.studentAge)
   */
  lecturePlanStudentAge?: string | null;
  /**
   * 페이징 구성시. 페이지인덱스(0부터),페이지당 보여줄 자료 수
   */
  offsetWithLimit?: string;
  /**
   * 정렬 설정. 필드.정렬방법으로 요청
   */
  sorts?: string;
};
