/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetReplyAndAttachedItemListParams = {
  /**
   * 자료의 키(driveItemkey)
   */
  driveItemKey: string;
};
