/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetStoryBoardListParams = {
  /**
   * 조회에 포함할 정보. contents:타입별 내용, > driveItems:내용+들어간 자료정보
   */
  includes?: string;
  /**
   * 페이징 설s정 페이지(0부터),한 페이지에 나올 수.
   */
  offset_with_limit?: string;
  /**
   * 정렬 설정. 필드.정렬방법으로 요청
   */
  sorts?: string;
};
