/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetStoryBoardParams = {
  /**
   * 조회에 포함할 정보. contents:타입별 내용, > driveItems:내용+들어간 자료정보, smartFolderItem : 마이보드에 들어가 있은 smartFolderItemResult(자료형태의) 정보
   */
  includes?: string;
};
