/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetStudentRecordParams = {
  /**
   * 조회에 포함할 정보. scores:항목별 점수, comments:평가내용, photoItems:첨부된사진,  smartFolderItem : 자료보드의 자료 정보 추가로 조회
   */
  includes?: string;
};
