/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetStudentFoldersParams = {
  /**
   * 특정 폴더 하위를 조회한다면 해당 폴더 id
   */
  parentSmartFolderId?: string | null;
};
