/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetTermParams = {
  /**
   * 입력한 연령.
   */
  age?: string | null;
  /**
 * 활동시간 타입. 단위_시간
MINUTES_20 : 20분, MINUTES_40 : 40분, MINUTES_60 : 60분
DAYS_1 : 1일, DAYS_3 : 3일, DAYS_5 : 5일, WEEKS_2 : 2주, WEEKS_3 : 3주, WEEKS_4 : 4주
 */
  activityTimeType: string;
};
