/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type GetTagsStartWithParams = {
  /**
   * 검색해서 가져올 최대 키워드 수
   */
  size?: string;
};
