/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { ImageTaskLogAddRequestTaskType } from './imageTaskLogAddRequestTaskType';
import type { ImageTaskDriveItemForAdd } from './imageTaskDriveItemForAdd';

export interface ImageTaskLogAddRequest {
  /** 이미지 작업의 종류
STUDENT_CLASSIFICATION : 아이 사진 분류
ACTIVITY_CLASSIFICATION : 활동 사진 분류
STUDENT_AND_ACTIVITY_CLASSIFICATION : 아이+활동분류
PHOTO_COMPOSITION : 사진 합성
PRIVATE_DATA_ENCRYPTION : 초상권 보호
SKETCH_CREATION : 도안생성
PHOTO_ALBUM : 앨범 사진 정리 */
  taskType: ImageTaskLogAddRequestTaskType;
  /**
   * 앨범 정리일 경우 아이 이름.
   * @nullable
   */
  studentName?: string | null;
  /** 작업 최초 생성자 계정 id */
  creatorAccountId: number;
  /** 작업 최초 생성자 프로필 id */
  creatorProfileId: number;
  /** 작업 생성자 ip */
  creatorIp: string;
  /** 작업에 입력한 사진 정보 */
  imageItemsForInput?: ImageTaskDriveItemForAdd[];
  /** 작업에서 생성된사진 정보 */
  imageItemsForOutput?: ImageTaskDriveItemForAdd[];
}
