/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { ImageTaskLogResultTaskType } from './imageTaskLogResultTaskType';
import type { DriveItemResult } from './driveItemResult';

export interface ImageTaskLogResult {
  /** 이미지 작업의 id */
  id: number;
  /** 이미지 작업의 종류
STUDENT_CLASSIFICATION : 아이 분류
ACTIVITY_CLASSIFICATION : 활동 분류
STUDENT_AND_ACTIVITY_CLASSIFICATION : 아이+활동분류
PHOTO_COMPOSITION : 사진 합성
PRIVATE_DATA_ENCRYPTION : 초상권 보호
SKETCH_CREATION : 도안생성
PHOTO_ALBUM : 앨범 사진 정리 */
  taskType: ImageTaskLogResultTaskType;
  /** 작업 최초 생성자 계정 id */
  creatorAccountId: number;
  /** 작업 최초 생성자 프로필 id */
  creatorProfileId: number;
  /** 작업 생성일 */
  createdAt: string;
  /** 작업 저장일 */
  modifiedAt: string;
  /** 입력에 사용된 사진 자료 정보 */
  inputDriveItems?: DriveItemResult[];
  /** 산출물 사진 자료 정보 */
  outputDriveItems?: DriveItemResult[];
}
