/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 하위 카드 리스트
 */
export interface LectureReportCardForAdd {
  /** 사진과 카드가 보여질 순서(0부터 오름차순) */
  cardOrder: number;
  /** 사진의 자료 id */
  photoDriveItemId: number;
  /**
   * 타이틀 내용
   * @maxLength 20
   */
  title?: string;
  /**
   * 카드에서 보여줄 내용
   * @maxLength 500
   */
  contents?: string;
  /** 사용자가 직접 편집했는지 여부 */
  isUserEdited: boolean;
  /** 해당 카드의 내용을 생성하며 응답받은 로그 id들 */
  lectureReportCardAiCreationLogIds?: number[];
}
