/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 놀이 계획의 대상 과정
 */
export type LecturePlanResultCourse = (typeof LecturePlanResultCourse)[keyof typeof LecturePlanResultCourse];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LecturePlanResultCourse = {
  KR_NURSERY: 'KR_NURSERY',
  KR_KINDERGARTEN: 'KR_KINDERGARTEN',
  KR_ELMEMENTARY_SCHOOL: 'KR_ELMEMENTARY_SCHOOL',
  NONE: 'NONE',
} as const;
