/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface LectureReportCardAiCreationLogAddRequest {
  /** 사진의 자료 id */
  inputPhotoDriveItemId: number;
  /** 생성에 사용한 활동카드 (놀이계획) id */
  inputLecturePlanId?: number;
  /** 생성에 사용한 메모 자료 id */
  inputMemoDriveItemId?: number;
  /**
   * 생성에 사용한  카드의 타이틀
   * @maxLength 20
   */
  inputTitle?: string;
  /**
   * 생성에 사용한  카드의 내용
   * @maxLength 500
   */
  inputContents?: string;
  /**
   * 생성된 카드의 타이틀
   * @maxLength 20
   */
  outputTitle: string;
  /**
   * 생성된 카드의 내용
   * @maxLength 500
   */
  outputContents: string;
  /**
   * 생성 요청자 계정 아이디
   * @minimum 0
   */
  creatorAccountId: number;
  /**
   * 생성 요청자 프로필 아이디
   * @minimum 0
   */
  creatorProfileId: number;
}
