/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface LecturePlanTermResult {
  /**
   * 놀이계획 시작일(yyyy.MM.dd)
   * @maxLength 10
   */
  startsAt: string;
  /**
   * 놀이계획 종료일(yyyy.MM.dd)
   * @maxLength 10
   */
  endsAt: string;
}
