/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { DriveItemResult } from './driveItemResult';
import type { LectureReportCardAiCreationLogResult } from './lectureReportCardAiCreationLogResult';

/**
 * 하위 카드 리스트
 */
export interface LectureReportCardResult {
  /** 카드의 아이디 */
  id: number;
  /** 카드가 포함될 보고서의 아이디 */
  lectureReportId: number;
  /** 사진과 카드가 보여질 순서(0부터 오름차순) */
  cardOrder: number;
  /** 사진의 자료 id */
  photoDriveItemId: number;
  /** 타이틀 내용 */
  title?: string;
  /** 카드에서 보여줄 내용 */
  contents?: string;
  /** 사용자가 직접 편집했는지 여부 */
  isUserEdited: boolean;
  /** 생성일 */
  createdAt: string;
  /** 수정일 */
  modifiedAt: string;
  photoDriveItemResult?: DriveItemResult;
  /** 관련된 ai 사용로그 */
  lectureReportCardAiCreationLogResults?: LectureReportCardAiCreationLogResult[];
}
