/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { SmartFolderItemResult } from './smartFolderItemResult';

/**
 * 이 섹션에 포함된 카드 리스트
 */
export interface LecturePlanCardResult {
  /** 카드의 아이디 */
  id: number;
  /** 카드가 포함될 섹션의 아이디 */
  lecturePlanCardSectionId: number;
  /** 섹션아래에서 보여질 순서(0부터 오름차순) */
  cardOrder: number;
  /** 카드에 들어갈 숫자 정보. 지금 상황에서는 활동에 대한 분수 정보만 들어갈 것으로 예상 */
  numericValue?: number;
  /** 카드에서 굵게보일 타이틀 내용 */
  title?: string;
  /** 임시) 타이틀 외에 보조로 사용될 내용 */
  subTitle?: string;
  /** 카드에서 보여줄 내용 */
  contents: string;
  /** 임시) 카드에서 보여줄 내용외에 보조적인 내용. ex)기존 기획의 태그정보 */
  subContents?: string;
  /** 생성일 */
  createdAt: string;
  /** 수정일 */
  modifiedAt?: string;
  /** 첨부된 파일 정보 */
  attachedDriveItems?: SmartFolderItemResult[];
}
