/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { LecturePlanUpdateRequestActivityTimeType } from './lecturePlanUpdateRequestActivityTimeType';
import type { LecturePlanUpdateRequestCourseType } from './lecturePlanUpdateRequestCourseType';
import type { LecturePlanUpdateRequestCreationType } from './lecturePlanUpdateRequestCreationType';
import type { LecturePlanUpdateRequestIndoorType } from './lecturePlanUpdateRequestIndoorType';
import type { LecturePlanCardSectionForUpdate } from './lecturePlanCardSectionForUpdate';

export interface LecturePlanUpdateRequest {
  /** 수정할 놀이계획의 id (LecturePlan.id) */
  id: number;
  /**
   * 놀이계획의 주제.
   * @maxLength 20
   */
  subject: string;
  /** 활동시간 타입 */
  activityTimeType: LecturePlanUpdateRequestActivityTimeType;
  /** 놀이 계획의 대상 연령 */
  studentAge: number;
  /**
   * 놀이 계획의 대상 과정(없으면 연령으로 판단)
   * @nullable
   */
  courseType?: LecturePlanUpdateRequestCourseType;
  /**
   * 놀이계획 시작일(yyyy-MM-dd)
   * @maxLength 10
   */
  startsAt: string;
  /**
   * 놀이계획 종료일(yyyy-MM-dd)
   * @maxLength 10
   */
  endsAt: string;
  /** (AI에서 응답 온 내용)AI의 생성 초점 타입 (TYPE_A~C) */
  creationType: LecturePlanUpdateRequestCreationType;
  /** (AI에서 응답 온 내용)실내외 구분(BOTH, INDOOR, OUTDOOR) */
  indoorType: LecturePlanUpdateRequestIndoorType;
  /**
   * 주요활동의 이름들. @!,$!로 구분. 없으면 주요활동 섹션에서 따로 체크해서 넣을 예정
   * @maxLength 80
   * @nullable
   */
  activityNames?: string | null;
  /**
   * 소유자 프로필 아이디
   * @minimum 0
   */
  ownerProfileId: number;
  /** 놀이 계획에서 수정할 카드를 포함한 하위 섹션들. */
  lecturePlanCardSection?: LecturePlanCardSectionForUpdate[];
}
