/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 놀이 계획의 대상 과정(없으면 연령으로 판단)
 * @nullable
 */
export type LecturePlanAddRequestCourseType =
  | (typeof LecturePlanAddRequestCourseType)[keyof typeof LecturePlanAddRequestCourseType]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LecturePlanAddRequestCourseType = {
  KR_NURSERY: 'KR_NURSERY',
  KR_KINDERGARTEN: 'KR_KINDERGARTEN',
  KR_ELMEMENTARY_SCHOOL: 'KR_ELMEMENTARY_SCHOOL',
  NONE: 'NONE',
} as const;
