/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { LectureReportUpdateRequestCourse } from './lectureReportUpdateRequestCourse';
import type { LectureReportCardForUpdate } from './lectureReportCardForUpdate';

export interface LectureReportUpdateRequest {
  /** 수정할 놀이보고서의 id(LectureReport.id) */
  id: number;
  /**
   * 놀이보고서의 주제.
   * @maxLength 20
   */
  subject: string;
  /** 놀이활동의 대상 연령 */
  studentAge: number;
  /** 놀이활동의 대상 과정(3월 오픈에는 사용안함) */
  course?: LectureReportUpdateRequestCourse;
  /**
   * 놀이활동 시작일(yyyy-MM-dd)
   * @maxLength 10
   */
  startsAt: string;
  /**
   * 놀이활동 종료일(yyyy-MM-dd)
   * @maxLength 10
   */
  endsAt: string;
  /**
   * 놀이 속 배움에 들어갈 내용
   * @maxLength 200
   */
  learningPoint: string;
  /**
   * 교사지원에 들어갈 내용
   * @maxLength 200
   */
  teacherSupport: string;
  /**
   * 소유자 프로필 아이디
   * @minimum 0
   */
  ownerProfileId: number;
  /**
   * 수정자의 ip
   * @minLength 1
   * @maxLength 40
   */
  creatorIp: string;
  /** 하위 카드 리스트 */
  lectureReportCards?: LectureReportCardForUpdate[];
}
