/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * (AI에서 응답 온 내용)AI의 생성 초점 타입 (TYPE_A~C)
 */
export type LecturePlanUpdateRequestCreationType =
  (typeof LecturePlanUpdateRequestCreationType)[keyof typeof LecturePlanUpdateRequestCreationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LecturePlanUpdateRequestCreationType = {
  TYPE_A: 'TYPE_A',
  TYPE_B: 'TYPE_B',
  TYPE_C: 'TYPE_C',
} as const;
