/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { LecturePlanCardResult } from './lecturePlanCardResult';

/**
 * 놀이 계획에서 수정할 카드를 포함한 하위 섹션들.
 */
export interface LecturePlanCardSectionResult {
  /** 섹션의 아이디 */
  id: number;
  /** 섹션이 포할될 놀이 계획의 아이디 */
  lecturePlanId: number;
  /** AI에서 응답으로 온 카드 묶음의 키 */
  sectionKey: string;
  /**
   * 이 섹션의 정렬 순서. 0부터 오름차순으로 보여주기.
   * @minimum 0
   */
  sectionOrder?: number;
  /**
   * 이 섹션의 보여줄 타이틀. ex)주제/목표/도입 등
   * @maxLength 20
   */
  title?: string;
  /** 생성일 */
  createdAt: string;
  /** 수정일 */
  modifiedAt?: string;
  /** 이 섹션에 포함된 카드 리스트 */
  lecturePlanCards?: LecturePlanCardResult[];
}
