/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * (AI에서 응답 온 내용)실내외 구분(BOTH, INDOOR, OUTDOOR)
 */
export type LecturePlanAddRequestIndoorType =
  (typeof LecturePlanAddRequestIndoorType)[keyof typeof LecturePlanAddRequestIndoorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LecturePlanAddRequestIndoorType = {
  BOTH: 'BOTH',
  INDOOR: 'INDOOR',
  OUTDOOR: 'OUTDOOR',
} as const;
