/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 놀이 계획에서 수정할 카드들.
 */
export interface LecturePlanCardForUpdate {
  /** 수정할 카드의 아이디, 없다면 신규 저장(3월 오픈엔 수정시 모두 있을것으로 예상.) */
  cardId?: number;
  /** 카드가 섹션 아래에서 나타날 순서. 0부터 오른차순. */
  cardOrder: number;
  /**
   * 카드가 화면에서 나타낼 타이틀.(카드의 최상단에 굵게 나와야하는 내용) ex)활동 주제명
   * @maxLength 20
   */
  title?: string;
  /** 카드에 들어갈 숫자 정보. 지금 상황에서는 활동에 대한 분수 정보만 들어갈 것으로 예상 */
  numericValue?: number;
  /**
   * 임시로 넣어둔 서브타이틀 텍스트
   * @maxLength 100
   */
  subTitle?: string;
  /**
   * 카드가 화면에서 나타낼 주요 내용. ex)주제 섹션이라면 단풍놀이. / 목표 섹션이라면 가을의 변화를 느껴본다 / 활동이라면 주제에 따른 세부 내용
   * @maxLength 300
   */
  contents: string;
  /**
   * 임시로 넣어둔 서브컨텐츠 텍스트. 기존 기획에 태그 보여준는 것들이 있어서 그런 용도로 사용한다면 사용
   * @maxLength 100
   */
  subContents?: string;
  /** 첨부할 자료의 id나 driveItemKey 리스트(3월 오픈엔 사용안함.) */
  attachedDriveItemIdOrKeys?: string[];
}
