/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 놀이활동의 대상 과정(3월 오픈에는 사용안함)
 */
export type LectureReportUpdateRequestCourse =
  (typeof LectureReportUpdateRequestCourse)[keyof typeof LectureReportUpdateRequestCourse];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LectureReportUpdateRequestCourse = {
  KR_NURSERY: 'KR_NURSERY',
  KR_KINDERGARTEN: 'KR_KINDERGARTEN',
  KR_ELMEMENTARY_SCHOOL: 'KR_ELMEMENTARY_SCHOOL',
  NONE: 'NONE',
} as const;
