/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { LecturePlanAddRequestActivityTimeType } from './lecturePlanAddRequestActivityTimeType';
import type { LecturePlanAddRequestCourseType } from './lecturePlanAddRequestCourseType';
import type { LecturePlanAddRequestCreationType } from './lecturePlanAddRequestCreationType';
import type { LecturePlanAddRequestIndoorType } from './lecturePlanAddRequestIndoorType';
import type { LecturePlanCardSectionForAdd } from './lecturePlanCardSectionForAdd';
import type { ApiTypeAndItemId } from './apiTypeAndItemId';

export interface LecturePlanAddRequest {
  /**
   * 놀이계획의 주제.
   * @maxLength 20
   */
  subject: string;
  /** 활동시간 타입 */
  activityTimeType: LecturePlanAddRequestActivityTimeType;
  /** 놀이 계획의 대상 연령 */
  studentAge: number;
  /**
   * 놀이 계획의 대상 과정(없으면 연령으로 판단)
   * @nullable
   */
  courseType?: LecturePlanAddRequestCourseType;
  /**
   * 놀이계획 시작일(yyyy-MM-dd)
   * @maxLength 10
   */
  startsAt: string;
  /**
   * 놀이계획 종료일(yyyy-MM-dd)
   * @maxLength 10
   */
  endsAt: string;
  /** (AI에서 응답 온 내용)AI의 생성 초점 타입 (TYPE_A~C) */
  creationType: LecturePlanAddRequestCreationType;
  /** (AI에서 응답 온 내용)실내외 구분(BOTH, INDOOR, OUTDOOR) */
  indoorType: LecturePlanAddRequestIndoorType;
  /**
   * 주요활동의 이름들. @!,$!로 구분. 없으면 주요활동 섹션에서 따로 체크해서 넣을 예정. 주요활동의 경우 LecturePlanCardSectionForAdd.isActivity를 true로 전달 필요. (섹션 타이틀이 달라질 수 있기때문에)
   * @maxLength 80
   * @nullable
   */
  activityNames?: string | null;
  /**
   * 소유자 계정 아이디
   * @minimum 0
   */
  ownerAccountId: number;
  /**
   * 소유자 프로필 아이디
   * @minimum 0
   */
  ownerProfileId: number;
  /**
   * 최초 생성자 계정 아이디(공유된 것을 저장하는 게 아니라면 소유자와 동일, 공유된 것이라면 공유한 사람의 정보)
   * @minimum 0
   */
  creatorAccountId: number;
  /**
   * 최초 생성자 프로필 아이디(공유된 것을 저장하는 게 아니라면 소유자와 동일, 공유된 것이라면 공유한 사람의 정보)
   * @minimum 0
   */
  creatorProfileId: number;
  /**
   * 소유자의 생성시 ip
   * @minLength 1
   * @maxLength 40
   */
  creatorIp: string;
  /** 놀이 계획의 카드를 포함한 하위 섹션들. */
  lecturePlanCardSections?: LecturePlanCardSectionForAdd[];
  saveFolderInfo?: ApiTypeAndItemId;
}
