/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface MyBoardRenameRequest {
  /** 자료보드 자료의 id */
  myBoardItemId: number;
  /**
   * 변경할 이름
   * @minLength 1
   * @maxLength 255
   */
  nameToChange: string;
}
