/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface MyBoardCountsResult {
  /** 사용자의 프로필 id */
  profileId: number;
  /** 공개한 총 게시글 수 */
  myBoardPublicItemCount: number;
  /** 공개한 자료 총 뷰 수 */
  myBoardPublicViewCount: number;
  /** 총 게시글 수 */
  myBoardAllItemCount: number;
  /** 자료 총 뷰 수 */
  myBoardAllViewCount: number;
}
