/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { MyBoardChangeShareStateRequestPublicState } from './myBoardChangeShareStateRequestPublicState';

export interface MyBoardChangeShareStateRequest {
  /** 자료보드 자료의 id */
  myBoardItemId: number;
  /** 변경할 상태 */
  publicState: MyBoardChangeShareStateRequestPublicState;
}
