/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { PublicUrlItemCodeResultRootType } from './publicUrlItemCodeResultRootType';
import type { PublicUrlItemCodeResultPublicState } from './publicUrlItemCodeResultPublicState';

export interface PublicUrlItemCodeResult {
  /** 공개 자료의 id */
  id: number;
  /** 공개 자료의 공유 코드 */
  code: string;
  /** 공개 자료의 스마트폴더 루트 종류(주로 작업) */
  rootType: PublicUrlItemCodeResultRootType;
  /** 공개 자료의 공개 상태. */
  publicState: PublicUrlItemCodeResultPublicState;
}
