/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 공개 자료의 공개 상태.
 */
export type PublicUrlItemCodeResultPublicState =
  (typeof PublicUrlItemCodeResultPublicState)[keyof typeof PublicUrlItemCodeResultPublicState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicUrlItemCodeResultPublicState = {
  PRIVATE: 'PRIVATE',
  PUBLIC: 'PUBLIC',
  PRIVATE_AND_URL_SHARE: 'PRIVATE_AND_URL_SHARE',
  PUBLIC_AND_URL_SHARE: 'PUBLIC_AND_URL_SHARE',
} as const;
