/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 빠른 작업 ai라면 이동할 폴더의 스마트폴더 api 타입(아마 Photo고정일듯.)
 * @nullable
 */
export type RecentTaskResultSmartFolderApiType =
  | (typeof RecentTaskResultSmartFolderApiType)[keyof typeof RecentTaskResultSmartFolderApiType]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecentTaskResultSmartFolderApiType = {
  Photo: 'Photo',
  EducationalData: 'EducationalData',
  UserFolder: 'UserFolder',
  MyBoard: 'MyBoard',
  PublicItem: 'PublicItem',
  Reply: 'Reply',
  Trashcan: 'Trashcan',
  Drive: 'Drive',
} as const;
