/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { RecommendationKeywordBundleAddRequestCourseType } from './recommendationKeywordBundleAddRequestCourseType';

export interface RecommendationKeywordBundleAddRequest {
  /** 추천키워드 묶음의 이름 */
  title: string;
  /** 추천키워드 해당 과정. */
  courseType: RecommendationKeywordBundleAddRequestCourseType;
  /** 시작일 */
  startsAt: string;
  /** 종료일 */
  endsAt: string;
  /**
   * 추천키워드의 가중치. 높을수록 우선
   * @minimum 0
   * @nullable
   */
  weight: number | null;
  /** 등록한 관리자의 id */
  creatorAdminId: number;
  /** 묶음에 포함될 키워드 */
  keywords: string[];
}
