/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { RecommendationKeywordBundleUpdateRequestCourseType } from './recommendationKeywordBundleUpdateRequestCourseType';

export interface RecommendationKeywordBundleUpdateRequest {
  /** 추천키워드 묶음의 이름 */
  title?: string;
  /** 추천키워드 해당 과정. */
  courseType?: RecommendationKeywordBundleUpdateRequestCourseType;
  /** 시작일 */
  startsAt?: string;
  /** 종료일 */
  endsAt?: string;
  /**
   * 추천키워드의 가중치. 높을수록 우선
   * @minimum 0
   * @nullable
   */
  weight?: number | null;
  /** 묶음에 추가로 넣을 키워드 */
  keywordsToAdd?: string[];
  /** 묶음에서 제거할 키워드 */
  keywordsToRemove?: string[];
}
