/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 추천키워드 해당 과정.
 */
export type RecommendationKeywordBundleAddRequestCourseType =
  (typeof RecommendationKeywordBundleAddRequestCourseType)[keyof typeof RecommendationKeywordBundleAddRequestCourseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecommendationKeywordBundleAddRequestCourseType = {
  KR_NURSERY: 'KR_NURSERY',
  KR_KINDERGARTEN: 'KR_KINDERGARTEN',
  KR_ELMEMENTARY_SCHOOL: 'KR_ELMEMENTARY_SCHOOL',
  NONE: 'NONE',
} as const;
