/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { RecommendationKeywordBundleResultCourseType } from './recommendationKeywordBundleResultCourseType';

export interface RecommendationKeywordBundleResult {
  /** 추천키워드 묶음의 id */
  id: number;
  /** 추천키워드 묶음의 이름 */
  title: string;
  /** 추천키워드 해당 과정. */
  courseType: RecommendationKeywordBundleResultCourseType;
  /** 시작일 */
  startsAt: string;
  /** 종료일 */
  endsAt: string;
  /**
   * 추천키워드 시작 연도
   * @minimum 2024
   * @maximum 9999
   */
  startsYear: number;
  /**
   * 추천키워드 시작 월
   * @minimum 1
   * @maximum 12
   */
  startsMonth: number;
  /**
   * 추천키워드 시작 일
   * @minimum 1
   * @maximum 31
   */
  startsDay: number;
  /**
   * 추천키워드 종료 연도
   * @minimum 2024
   * @maximum 9999
   */
  endsYear: number;
  /**
   * 추천키워드 종료 월
   * @minimum 1
   * @maximum 12
   */
  endsMonth: number;
  /**
   * 추천키워드 종료 일
   * @minimum 1
   * @maximum 31
   */
  endsDay: number;
  /**
   * 추천키워드의 가중치. 높을수록 우선
   * @minimum 0
   */
  weight: number;
  /** 생성일 */
  createdAt: string;
  /** 수정일 */
  modifiedAt: string;
  /** 묶음에 포함된 키워드 */
  keywords?: string[];
}
