/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface RenameRequest {
  /** 요청한 사용자의 프로필 id */
  itemOwnerProfileId: number;
  /**
   * 변경할 이름
   * @minLength 1
   * @maxLength 255
   */
  nameToChange: string;
}
