/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type SearchMyDataParams = {
  /**
   * 검색할 키워드
   */
  searchKeyword: string;
  /**
   * 특정 파일 타입을 검색한다면 파일 타입. (enum type 시트에서 DriveItemFileType 확인.)
   */
  filterFileType?: string | null;
  /**
   * 오프셋 개수(이전 조회의 nextOffset)와 한 페이지에 나올 수.
   */
  offsetSizeWithLimit?: string;
  /**
   * 정렬 설정. 필드.정렬방법으로 요청
   */
  sorts?: string;
};
