/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type SearchStudentDataParams = {
  /**
   * 검색하려는 학생의 id (검색 대상)
   */
  studentId: string;
  /**
   * 검색 시작일
   */
  startsAt?: string | null;
  /**
   * 검색 종료일
   */
  endsAt?: string | null;
  /**
   * 검색할 타입이있다면 전달. (or검색) <메모 : TEXT_MEMO, 음성메모: AUDIO, 사진 : IMAGE>
   */
  fileTypes?: string | null;
  /**
   * 즐겨찾기만 본다면 true로 전달. 아니면 false 나 null로 전달.
   */
  isFavorite?: string | null;
  /**
   * 페이징 설정 페이지(0부터),한 페이지에 나올 수.
   */
  offsetWithLimit?: string;
  /**
   * 정렬 설정. 필드.정렬방법으로 요청
   */
  sorts?: string;
};
