/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type SearchMyBoardDataParams = {
  /**
   * 검색을 시도하는 사용자의 프로필 계정 id
   */
  requestedProfileId: string;
  /**
   * 검색할 키워드
   */
  searchKeyword: string;
  /**
   * 페이징 설정 페이지(0부터),한 페이지에 나올 수.
   */
  offsetWithLimit?: string;
};
