/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { SmartFolderItemResult } from './smartFolderItemResult';

export interface SearchListResultSmartFolderItemResult {
  items: SmartFolderItemResult[];
  size: number;
  nextOffset: number;
  total: number;
}
