/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { ReplyResult } from './replyResult';
import type { SmartFolderItemResult } from './smartFolderItemResult';

export interface SmartFolderItemReplyResult {
  /** 자료의 물리적 키. (DriveItem.key */
  driveItemKey: string;
  /** 댓글 수 */
  replyCount: number;
  /**
   * 남겨진 댓글 리스트
   * @nullable
   */
  replyList?: ReplyResult[] | null;
  /**
   * 남겨진 댓글의 첨부파일 리스트
   * @nullable
   */
  replyAttachedFileList?: SmartFolderItemResult[] | null;
}
