/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { SmartfolderApiTypeAndIdRequestTargetSmartFolderApiType } from './smartfolderApiTypeAndIdRequestTargetSmartFolderApiType';

/**
 * 원본 자료의 자료 api type &  id 리스트
 * @minLength 1
 */
export interface SmartfolderApiTypeAndIdRequest {
  /** 요청하는 자료 Api type */
  targetSmartFolderApiType: SmartfolderApiTypeAndIdRequestTargetSmartFolderApiType;
  /** 요청하는 자료의 id */
  targetFolderId: number;
}
