/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export type SmartFolderDocumentItemInTrash =
  (typeof SmartFolderDocumentItemInTrash)[keyof typeof SmartFolderDocumentItemInTrash];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SmartFolderDocumentItemInTrash = {
  OUT_OF_TRASH: 'OUT_OF_TRASH',
  IN_TRASH: 'IN_TRASH',
  PARENT_IN_TRASH: 'PARENT_IN_TRASH',
} as const;
