/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { SmartFolderDocumentItemRootType } from './smartFolderDocumentItemRootType';
import type { SmartFolderDocumentItemFileType } from './smartFolderDocumentItemFileType';
import type { SmartFolderDocumentItemPublicState } from './smartFolderDocumentItemPublicState';
import type { SmartFolderDocumentItemInTrash } from './smartFolderDocumentItemInTrash';

export interface SmartFolderDocumentItem {
  id: number;
  rootType: SmartFolderDocumentItemRootType;
  parentId: number;
  driveItemKey: string;
  depth: number;
  fileType: SmartFolderDocumentItemFileType;
  internalId: number;
  name: string;
  publicState: SmartFolderDocumentItemPublicState;
  hide: boolean;
  ownerAccountId: number;
  ownerProfileId: number;
  creatorAccountId: number;
  creatorProfileId: number;
  driveItemCreatedAt: string;
  addedAt: string;
  userEditable: boolean;
  inTrash: SmartFolderDocumentItemInTrash;
  internalType: number;
  relativeMonth: number;
}
