/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 요청하는 자료 Api type
 */
export type SmartfolderApiTypeAndIdRequestTargetSmartFolderApiType =
  (typeof SmartfolderApiTypeAndIdRequestTargetSmartFolderApiType)[keyof typeof SmartfolderApiTypeAndIdRequestTargetSmartFolderApiType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SmartfolderApiTypeAndIdRequestTargetSmartFolderApiType = {
  Photo: 'Photo',
  EducationalData: 'EducationalData',
  UserFolder: 'UserFolder',
  MyBoard: 'MyBoard',
  PublicItem: 'PublicItem',
  Reply: 'Reply',
  Trashcan: 'Trashcan',
  Drive: 'Drive',
} as const;
