/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface StorageUsageCreateRequest {
  /** 할당할 드라이브 사이즈.(byte) 기본 100G */
  sizeAssigned: number;
  /**
   * 생성 요청한 ip
   * @minLength 1
   * @maxLength 40
   */
  createdIp: string;
}
