/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 지표가 해당하는 교육 과정
 */
export type StudentEvaluationDomainResultCourse =
  (typeof StudentEvaluationDomainResultCourse)[keyof typeof StudentEvaluationDomainResultCourse];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudentEvaluationDomainResultCourse = {
  KR_NURSERY: 'KR_NURSERY',
  KR_KINDERGARTEN: 'KR_KINDERGARTEN',
  KR_ELMEMENTARY_SCHOOL: 'KR_ELMEMENTARY_SCHOOL',
  NONE: 'NONE',
} as const;
