/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 첨부된 사진들
 * @nullable
 */
export type StudentRecordAttachedPhotoForUpdate = {
  /**
   * 관찰기록에 첨부된 사진의 id (없다면 신규로 등록)
   * @nullable
   */
  studentRecordAttachedPhotoId?: number | null;
  /**
   * 사진 노출 순서, 0부터 오름차순
   * @minimum 0
   */
  sortOrder: number;
  /**
   * 첨부된 사진 파일의 자료 id
   * @minimum 0
   */
  photoDriveItemId: number;
  /** 대표 사진 여부 */
  isRepresent: boolean;
  represent?: boolean;
} | null;
