/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

/**
 * 그래프에 들어간 항목에 대한 점수들
 */
export interface StudentRecordEvaluationIndicatorScoreResult {
  /** 평가 지표 점수에 대한 아이디 */
  id: number;
  /**
   * 관찰 기록의 id
   * @minimum 0
   */
  studentRecordId: number;
  /**
   * 관찰 기록 대상 학생의 id
   * @minimum 0
   */
  studentId: number;
  /** 평가지표 뎁스 */
  indicatorDepth: number;
  /**
   * 평가지표 코드
   * @maxLength 3
   */
  indicatorCode: string;
  /**
   * 평가 지표에 대한 점수
   * @minimum 0
   */
  score: number;
  /** 생성일 */
  createdAt: string;
}
