/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { DriveItemResult } from './driveItemResult';

/**
 * 첨부된 사진들
 */
export interface StudentRecordAttachedPhotoResult {
  /** 첨부에 관한 아이디 */
  id: number;
  /**
   * 사진 노출 순서, 0부터 오름차순
   * @minimum 0
   */
  sortOrder: number;
  /**
   * 관찰 기록의 id
   * @minimum 0
   */
  studentRecordId: number;
  /**
   * 관찰 기록 대상 학생의 id
   * @minimum 0
   */
  studentId: number;
  /**
   * 첨부된 사진 파일의 자료 id
   * @minimum 0
   */
  photoDriveItemId: number;
  /** 대표 사진 여부 */
  isRepresent: boolean;
  /** 생성일 */
  createdAt: string;
  photoItem?: DriveItemResult;
  represent?: boolean;
}
