/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface ToggleHiddenItemsRequest {
  /** 요청한 사용자의 프로필 id */
  itemOwnerProfileId: number;
  /** 상태를 보이기로 변경할 위젯의 id 리스트(SmartFolderResult.id), 전송한 순서대로 배치합니다. */
  targetItemIdsToShow: number[];
  /** 상태를 숨기기로 변경할 위젯의 id 리스트(SmartFolderResult.id) */
  targetItemIdsToHide: number[];
}
