/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface ToggleHiddenItemRequest {
  /** 요청한 사용자의 프로필 id */
  itemOwnerProfileId: number;
  /** 상태를 변경할 위젯의 id(SmartFolderResult.id) */
  targetItemId: number;
}
