/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */

export interface UpdateTaggedStudentsRequest {
  /**
   * 태깅한 아이가 있다면 그 아이의 id 리스트 null이나 빈 리스트로 오면 기존에 태깅된 내용 삭제
   * @nullable
   */
  taggedStudentIds?: (number | null)[] | null;
}
