/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * File API
 * isd / kinder board api doc
 * OpenAPI spec version: v1.1.0
 */
import type { UploadedItemInfoType } from './uploadedItemInfoType';
import type { UploadedItemInfoFileType } from './uploadedItemInfoFileType';

/**
 * 업로드한 항목 정보
 */
export interface UploadedItemInfo {
  /** 항목의 종류. FILE, FOLDER, PROJECT,TEMP,ROOT */
  type: UploadedItemInfoType;
  /** 업로드한 썸네일 파일 객체의 id */
  thumbObjectId: number;
  /** 파일의 종류. URL,DOCUMENT,IMAGE,VIDEO,AUDIO,ARCHIVE,ETC */
  fileType?: UploadedItemInfoFileType;
  /**
   * 파일의 종류가 url일 경우 그 url 정보
   * @minLength 1
   * @maxLength 1000
   */
  url?: string;
  /**
   * 파일의 이름
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** 파일의 사이즈(Byte) */
  totalSize: number;
  /**
   * 별도의 썸네일 url이 있을 경우.(fileObject.host/fileObject.bucket/fileObject.key)
   * @minLength 1
   * @maxLength 1000
   */
  thumbUrl?: string;
  /** 프로필의 id */
  creatorProfileId: number;
  /**
   * 업로더의 ip
   * @minLength 1
   * @maxLength 40
   */
  createdIp: string;
}
